apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:2h4itllI/dFMVtY71jY1SI/isa+GfURzmL6wSNyaw7bj73cRilWLBw==,iv:WtarJSpGZo+f0MllX9x04r/49sTXD7A2SKvUiKDNmhg=,tag:hYQzyYafgcXkqGRAKZ/sqQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKM05ncXhCaU5PL1g5eXlt
            dG52ZXRtWTdmQmtKNGMvQ2Z6STVkenlGQmtBClRmYktrR2ZhUFZROFdoM3ZtZU8x
            TjgvZHh4elZTSG85L3VtcWdtS3RkN0UKLS0tIEtsSWdSYk92Sjh6WkZ1ZFBZRzho
            RnRYbW1GU0Q4d3p1dFZZdjRXN0tWbG8KiPTEQ2eaSU+bHz+ZTNHtEu0GALscMwiL
            TwmM8GnzA4iiKljbM5Gs0CsXMTo6WHW+Z5khRnSWIS+rGcwVkmJpXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T13:07:29Z"
    mac: ENC[AES256_GCM,data:x7oNk/fX8Tb3377WQBNJd2GfhbwzxPa01NWefcB50g1rL6roqppYG2Kb9U7D7lGPxBk/nOZeRP9b+ZtHjV+eobRx+LextHQezzaagMp9Zk7+zpyLHxegWs+NWI7OgZ4ebe4y32qDoGKTHrIhwqx4RYwmEML8YODbTAA2pJtGIxQ=,iv:tvm7I/T9UFsCoV+UtzqO9Dz1MTr0H6yGiCA2RfZWOjM=,tag:8WYUL9ZUv2c0E0eAqTy+UQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
