apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:4J9IDcCMIPvYIinpUps+9FUtHHSFmYAPXB9DQdOzLK8AXER9cIgZfQ==,iv:I7UgNjah4lpk4Y13PpLNk9igoT70afnfWUCj96Z6vOc=,tag:F8h2pZqz3dyZuuuJmOs84A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbThCQ1RRdDE4c2NYTEpT
            cFd3aDhJYTV6dHVWRUYyTVkzeFNCa1Zxcnl3CjRxY3NIWUtJdDVERm9UU1l0V1l1
            QmN0TVU4SmVKUTltYlNjRmgyaVZRcEUKLS0tIHNBYU1WUDV2U3J3ZTNoT1lLWGhH
            c2R0bGduWUxDQW5JZ2paeERDOXFXVncKDu9x2rPVyeh/2Tj52BBo/8kxwZGT8JOI
            lhOWOVQ7XMWxK/TgOqFd2lw58PwOhXJFqqp/bAda3GBIJYk5E25+9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T13:06:53Z"
    mac: ENC[AES256_GCM,data:+CcIk4SCVekn8SahWF1lPo1oNha53tcINRz8q49QeizIrLiDxIMpWmf4vj2xACaBIhVPmqwZE1MwGueeHXoxv1fY27mNAONy5r1ndIal837ioNmqHNDh1/t/qbfJ/88AdSFFGVkT2DNHxHZ1hblHxJ0Gi/32WKAuLcMAwt7+IZA=,iv:bIHlAvGMUY3bwqZtpMWuf5AS/4TgE7cTEe70CIcihKw=,tag:CUg07pKjINYAy+ONDQfdXA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
