apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:r4g4aN0oiF7AK0KHcUNykiq328WNT2lRS5TMRTga8GOs+mtka7kH2A==,iv:SOIuZEI3iJOdMDMz+0hnXC7/2cfZn1urTecICyZTLpk=,tag:XPYQDDOwk8hxHXlU/LK3eg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbkc2OXFHTU01SFkyNjFT
            ODBWOEVNdXBRZzdXSHZCOG1FREcwcFIrUEhFCnJJekxmam1BTlRaRWxWNVlmdWY2
            WmpPb2daQWdTRFd3b3kwM1lhMXRoakkKLS0tIHRNUVdtSWtwMzVIRnVyYjlSUm1w
            NldtdUdCZWNOaFYzdXN3b21MdXQ3TGMK29cjl1AZ1Rc9YNFdmxw9XBToSS/w5oCO
            b89XMcdRfA5YGfhzUTB9s9IWJrcRPSvDH5sApAQMMOnGkmk5j+BmuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T18:20:53Z"
    mac: ENC[AES256_GCM,data:JneO4KbQ0830CE+UoJHCSLVchJn48pFdRUsHgRqLa0q0A2nIAx0+jqHdZR+W5a0k0vG7vxsisxf0OzxdUDnNvzZq6+3t3GIhTtKr2V1yGhwbaG6/cPCeMXpYnPmalkj7rnju1X2o0pNvLkIraBF3k3Pqn3EIiLshPUy8wjHRzwY=,iv:kFxzd0/h3/3fZRnjrUPMFzPaS4lFKT8tn7zvK7cz5QY=,tag:b+F5gFfbqtIhpejFeQNoMg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
