apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:rAbafVv9fANYFSbY0ae3lSQc+LEMP5Lio+og6Qmg00C1n2apfZLVtQ==,iv:zv8oOsBYhT4NkEE/iZrCzbaeC43lyyzfZunLZDsCg64=,tag:RZG9jkwyfEvg7vY71E0iKA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZmk1bEUyU1luM29yNlFy
            VG5YdXhSLzYwUXF4MU5vcjZLTDk0d2FwcW1NCmkwODNwR0h5VUUwWGs5WlQ3TUYw
            VDRxOTVaVVBDaHNKSEozbjU3SHA3ckEKLS0tIGEvMTYyc0x5TzRlYjhTaC9YR1B0
            dVdOeUJMcGVSZ3dPUzdNNFBqVFhxbTQKDCyGIIr1V9U88fRcsv3fQJPMJZnwj3Vv
            IFdijUgNLkwR4bLOUwx0qjdzXMcV9v4bXOz1yke+x1B6lN7O4xGjAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T15:16:44Z"
    mac: ENC[AES256_GCM,data:CjBDK/EUQECKqHsaHHD55KPJlLgPq9v82LIlvinDvRg06vWgY2rEYvTClWkCymU1J0lW+8DW/xhb3ct4Wq3q57Elp1W0UdIAFKAFjQCT+NkvK5boYRrV6NtHZy1ADeKdyRikYLp8GLK5ixzEvCbIFy0cPt+empvRTQve1E0RAps=,iv:kkTNhu8MJU6Rw9mDY5oM+seF4ZHNrCMamWG4+GxVMr0=,tag:yH2waTv5F3jlRj3cUq/1vQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
