apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:I8o6i6HTBtugsZyaBtx3T+2cNBELqrEfB3ad2/4b+S68ViPZbHVy5w==,iv:wbilSMlRtHlZtBs7i9cWCRLnD53n/BHNq4vrYpJCkIM=,tag:tHr0Sk/0ICzV7eKCot+WLg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxa3FCNktweXJkOStZMHJp
            em9YRzFweTFHNGJnZ0IxNlBjc0RvSEJtcDBjCi81b0FRblFWczU1TEt3ME4rS1NG
            NFVJM0dyTUVwU1pibjROYnoyZUQ3Um8KLS0tIGl4Q1hDd3BTWksyaU4rTklMU3dM
            dUxPVS8vNDhaY1hHbnBzUGp1WE4zQzAKbbOsFyb6xgR/lAAQNYwCZkz+x2e+MDbh
            gX3EzePpw69xraV4fkVMXkFrXI8bFma/I4C8mOI4YeRCs5pUXpZNlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T09:54:20Z"
    mac: ENC[AES256_GCM,data:ePcfWMIH/18CM7dy6X3PTyqpTjA1uIyH3CgSP/695PPZD6PNSRwm6RLY5l98Cn6l06Unaz9rqVZYoscV+pf60XuTWXy+G0TZFyArNVCYm4e/5FTAZr3LALyC55bPN1AtkAl1GsOy7j3HO72wMUCdOT7FkZE/G5LU9r8grri38h4=,iv:rn7kBYsBPl+1+61baoY4LbYAWriK8SNKzqHKSWGq1H4=,tag:2xMm7N6hV9unTjm8lmWAeQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
