apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:D5wS6SxsGO+NGSxWVFRJBi82PrqTfPFXIgammmZFzF0i+/N1ZEt9gA==,iv:em1sCAtAsl335N11SAe8L+pOv1FEiOZTS70tSshq7eM=,tag:DgugAUhHGvNsaTbSSQvwxA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSK0NZWVd6MEJ4a1IzcUh2
            OVVjYjFOL0FGeDN2REppSGZtUHQwMDE0VlhnCmVUZ1lxMFBzTXQreDlNdTNUcFZQ
            QmRRRkYxR2JoQzJoZmszT204Zmh1aVkKLS0tIHlFWjlLaWFlaldFT3FWL1dvRG5q
            dFBhV2xJdHlyc0JXSG5DSzBpODRHQXMK6GD3U8EkjbRJt2IT0yJA3d3gSKwAQjxO
            EEw/a45kQQzDF5yHo8Cc2SuoKXzy2msgDnr09MLe9buGSGOJrno//Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T14:23:53Z"
    mac: ENC[AES256_GCM,data:wF2dK39ZL6Dsqrw+zCvtJNpRy84jW2sIl32kdfpeFqeXPFPE+p1cdMqyOzIwplMGLAwQxidbFj10M4AZkP9bZvPuQlXVA1ZfEdyl7hVVHcJSuipFotTkYgFc5IC0VlKihdFemFpqibaiGbBZCaU9LP0COIXP7q0aACdwAr5yPYY=,iv:bv8LBUN6Mfi+nAt5iRivErhzmp7l2rSdXprmsT9+u4k=,tag:wkKLKjifURK2z3qF+j61tw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
