apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:6JRm50khbPsaDxliyBt/JmEW8EGBScrZl5tVtWb7eeYc3RDTc9o9cA==,iv:HCtWtJ4OyR/6sV1ucnSJDE4UFcTJlmfiE49/kArFfc8=,tag:MXmddCfGgKm06ArgypA1yQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzS0RJSHl2MmpNQndESmdH
            M0Fwd0YyWnQ5bXBUd0Qzc3k0Y1VvNGVnbHdnCk9Zb0dnOTFCMFU4QmNubnpCMjI5
            aUVzbnRHb091ZkVvQ3NIQW5uMkJuUE0KLS0tIDZYL0pxU1kvTGRoNFI2Mm5TbG9R
            YzNKZStOTENVdFRvb3ZVVVh6bzVOWTAKv8/fWtZvZfbVTJWufWJOAgCNtOOcTkh9
            yU/h62QD9fJi+1ei0HzXrmd8MbV5v9Yxy8LQmxi/Lx1zmPSOezEt0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T12:58:30Z"
    mac: ENC[AES256_GCM,data:1eqgJZBZtKw456uV1IxYO+FV5DY7GZ2e6P0WcZ//x93P66U8/zjIlPi5iItlqzGUdT8HPEdUV6ynw2tkpDBIQutmYHQX++6hOCF6jTurYvfoEfAP8XiQhBYog2bx9Z9TLgry3aXF8v8D1eWkObZk/wiObbDI9p0MJPbzNaCJJfc=,iv:GhKuy933T9rrDow2lSqLDGPEyY5N2569679DUBf+VE0=,tag:EhAXNCYS6OT8ghII7RZaPg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
