apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:11YD18qVFCScGllwoMY4UO0nGzbd/RneI4e/Qz2XUonkscs8O99Saw==,iv:Iqa2YHGYocdUYNm6v572ndJCBoTq6gb5/J2tP+hC/5U=,tag:P3EA+4zRVOgfvz370vKV7g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUzMzcEw2UDk3STNTYllo
            ZUZpaWhZMXF1NzFtM1ova3pJZXMyQ0dlSlY4CkhuWkdzSUM3WU5OdW9CSlFXL3Vp
            UG9oZkh5TWdTdkQxb0NrVU1Sek5ETXMKLS0tIDVaQ3Y5NHNoNnlwUWlMLy9EWnVR
            ajVzZ09GTXoveXlSdEQvR2FWazBBK3cKQrI4BpZhTMWEUAT+HPRR1M4XpQHymfG2
            y76ALtFDKOiet2L4/2GtMBKYxM3JplG5Pw9oO8WW3/Ug8XdSHCebMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T15:51:32Z"
    mac: ENC[AES256_GCM,data:iFbwPkdxWP+YgtVvmd++L4u1BbKWuwLJTPQLb2Q8u2iajAQwO4W3N30+2vkD9AP8BlsglKczSx9+X9RGtVwduOdEVh6hMBFNHT0CX09wJAOnYaytS1Fm8Qz0YrvhhSlGwCs+GgB3UfBLH5S6N+bCIi/BlBcFYaDmveWqFQzp3b8=,iv:2ozKqQopC4M3vVhHx1fnkxwY99HLP0Q5BE2y/ET5FSU=,tag:RCN4kX4cPY4pI3f08iRslQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
