apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ZOG/joygJgJp2gRn046MLbfbJbl8T8dgAaWbQ4LxTIf/vurweuNo0A==,iv:A+5uRZw8zgnXi5xIRzEaohSq6PfxnyOnqlvRR8y72D0=,tag:lOGQtL/VnYe10vPaRUrcFg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNTAzSXRvV0dPbG9DYVJy
            UFl4VzFISS9WUE5WVWRXRkpvOWdSR3BNeFVJCmc1R1prY1h4Z0dXOUlReXpxRU0w
            bi85ZGJ0a3V2TjhmS29YOGpOVUJ1cEEKLS0tIEJ5Z3hORkhIbjRYdXFkamcwUnh2
            YW9wMDRXYlM2WUwyTUlzL1g1Q1lVa2cKo1XFgIrJpy5AEGzRhIByXut2ozJvqWDZ
            6W0rV5/wcEc7l9P1nEXEvOr3VxtT4K4qBS7sh7ThocQ6emm8sdwNXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T13:34:45Z"
    mac: ENC[AES256_GCM,data:pMalSlYUfkKcAMtll6jB/vXh58NnjFoFptOuFQHUSNb0DTMDuuVUSg88aoettFpX/8FpckJI2Ohj44vPm2vbRRp5plPHe7SwWxnnmbQkIy5brnzzkpmFbrtBvdR4JfBKujT9g24lAHu8zSZ5etT9LMQFiEnto9wD0O009wrlvrw=,iv:FdrjgwvS9H9m3D5+HcJq5MvXSd307JLY6FbJ9k2bmOE=,tag:8qkeI6fGz0k9eolva3Zlqg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
