apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:HUC4khgCMtC3YRP0qUIlNJizv52C0GIdcv96m3ch7i+79ZkVTvEdMg==,iv:UhBhIgtlTyjtWITWmw6BmDXAvAHqXWaE77DKW5mD7Zs=,tag:qslJuAWYdDr3PAP+U2rhew==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WU1ua043V0xISkpwMkVI
            eVVBQUFKbmh2TFBGRG9VamQ2bzI2NWdQempRCnFuanRYM3E0dytFclZKV2RpTEVW
            UzFMYXIwUnovYWc2L3hQZGRDYlJWWUUKLS0tIGwwNDdpZU95aEtra3dkRmNsWmVF
            ZnIzcFVEVDVleEhOZ0tlQVhHTEpYbEEKwyKbRgL63bd1QJcGF+e2hUfD3CK+x80l
            MYKIkyNjVZNZqOGhSPWPO8PVVm7XkyIC57qZY1jKxQtSrQfQ3Zt1rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T23:36:07Z"
    mac: ENC[AES256_GCM,data:8y8Rbkt8FFEKGgfJtsXup4WBio4pdo3uMfZWZMwwatGcLYUeHlIRfAnn9n0B+ogtoHEVSjs4t4VLjCgyTx4orhwPHz6LZcVxl1imFQuRMxZPLF4TBpi3gMqURF6RnZxGbt5+lLUVDzN/EQwt8KuzyOHH1JcqigAY/FQSRlKDH5k=,iv:hs6LYcPtU60LcpB0DZFCuzq/t/22g6znaq8MwzO8z7g=,tag:1u87MncMHFCmtd0fGjIvMQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
