apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Yx4iggxDiSJUW2DWbZ7clSKcN1tO+SMk+4/x8DEsnqQBkhWk7RItXg==,iv:Bz66cN4fM9+3Ot+Mi2kHQ3h1aPa6++V7/QbGD4P+nJE=,tag:CzGhYjgGNYh6WLC+ib1DWA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cHdwVWFKVTdNNkE4cDBU
            QWlnd29QQmduaGYyWTZZZElXZjk1TWFWaDFRCkI3aEw1L3Z1eTZFYzVJVHYvRCti
            NGZEeXQ5L3NpNTd1SDJuZTRkTzhFaFEKLS0tIFlNVVk4eW52THkwK1dGWFEyTVlu
            b0FIWGkvSUpkZ3hYT21SdlAwa0cwK3MK1XISlu7x0dlNpf5BlW3Pv+Sc6U9rZUwp
            7wXsguH93auEMLrTCVfgxU/DhuP+msW6WZM3QRIVY8i8q9/V1pzznQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T15:07:18Z"
    mac: ENC[AES256_GCM,data:HiMVk9Vs/jmdi5P6vRemnZtLSuxTtoq73r23d2+fbFG+9xuw17h0nNe6Fv6XH5VnyM0hdL5hkp5683KY8rcjK/YYbgeL0kJeafGABiumRsQCN+jILFn5Kvi/PSP9nqn4yU2XVoT5NsrcbYlpfVAtqe9x+FSsnxvD6hT6HxRFkco=,iv:hF0nDPaiKnUZ1Uckba0iE0XXbWkX834xP/ub7TqYtA8=,tag:mFjuhXSE55GeEuQL6IrgSA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
