apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:dbwwZaGVIaCx1CGUGCZd5poeGgwJrUMBkZo5ewwEC7XeDLz+O5LCMw==,iv:Cj3XFsdTNYZkiDiDO37UYn5mpw7tAI/Hmo9Iek+pfyk=,tag:PxF3oYjF2WUyKDG77ADt3w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRDNXR3pFYmJHZ3FLU0k3
            WFNwakoxczBtOTI5aXM4cjdIYU0yUjlzNWtrCk1JOXNkU0kwSmxkemdNNlBhb2Q0
            bnVWQlhzSGt1djhRbTBYS0djTlJlZXcKLS0tIDNZSm9YcmJzNGN2QzNZSTg5Mk9r
            RGliWTdwRS9JdmNlVG1KTHVPcnhaaWMK/IvQbOkGQ5gilyL9TDmPS8c0SPzEQX+f
            HZ9OiSN3lc+jdr9pfIddA81tvQVGr9BIerI7ZHrWxyUVb5OeJ8yzIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T15:42:20Z"
    mac: ENC[AES256_GCM,data:EgcqF98o0l87q3MunbGcUvcUAh0D9QCmzeCRy+d8EmSChR36zBcfRO+vmG9kbIWUHGqtMU2li/GcRMPUlVb6A5YrOO83BGjPai1jmfsKIz7+ySA1rPpkyzEG3LBQV6zOJcvnCFKYkWJjd/v9MfvdiLgoqQcsBeqNV6DwHnNdYrs=,iv:T5OW6nW7wigYrjkkszUqXVxBR0hsbz5mrj2jDH+GwQ0=,tag:T2MYRB/xJkFCIv4BOl7v+g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
