apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:9fhYsXmfM7y3nAoWYQIDq6lXJ6c9SGap5I+HCJh3UQHSR6RVSeAFNQ==,iv:OXIWSabNLsJFhaWip0QjGGfEy9y53KcbM9B9+PG5tRo=,tag:w7X7VD8b7GFDGIcABPMQTA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYXhzUk90QkdIeVIraEsw
            eXR3Z2pyVmhVZ3FyMityY1JHK1c2ckpwc3cwCkNMMVlBT0FhdVBwSUtmdTU4ZW9t
            M282cEY4dnhiRDVVYnNFa1lLeFE4bjAKLS0tIGhobXliS3JPekM0R3JzTEVCbWh4
            bWh0cnpueGhHYlUyRWoyc3JFZm1HVzgK18HuETY+mJr8amPely+HnzuI2iOMWFXm
            ryI6+OnTzevqkusisa3rWzjuskrCA2LA7WHKOONRD+aJTq85zrrChw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T15:06:34Z"
    mac: ENC[AES256_GCM,data:RGDTyfbxqRQb0k9XWCJnaItNL04AgQgq9b/UKcS9cB5Nf4dvQSblmWuBHWXMRjDnSqTNC3FIwfzYb9OzFGTx4hMqQ9LYiLDZZiQwnJQyI80HSSxTh96RKKWS6W8yW+DSuyj+43OKGSm/TSGH8rDPz/XZDqWUFN4HFR53QzHyAzY=,iv:CF5tVHJ0H6fcHACrb8vmoYiDWM/I8MqO5wR5zfxk0js=,tag:pWpipiaGMIUsgIx9RK9ZSg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
