apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:zFwNXEWE+JboN9usLVPDN3sY5TaZuKqbI/p9hv4ERr94ccOpu8cHzw==,iv:laIXFA0VN+NK5fU3p1GufevEyyenTi4mcsnoyfKWQ9A=,tag:NQJ//XSexY/bjuisPN2ulQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVkF6TjZSeHJTQTQ5ZkZw
            cEJhb3F3Q2s2RURCRmh1VExKV1V2a0hzM3hBCkNWbnpESUpMUHp0WmxIS0FoZUpQ
            NkRkTU9BY3BjOC84cXdzcExiWk80N0kKLS0tIDBaQ0E2ZnBiR0dwNklRbi91b3lO
            REFyS0hXbHc3WlRlSWdYQTRGNi9NbDQK1fd+oqkf/U4745iA5ZdXcN9QEr7A00FN
            GnfLpbiYiK3TmiZEOamACrgCEiNigAQA6AvjNWeip47hYFBebGckLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T09:51:57Z"
    mac: ENC[AES256_GCM,data:bNqPc+hLW7/Uw2zmgfWUAYNujYoCcU9zyOb1bqBx3dtU8Fze3qYONsw36Z2J4T65qL45+Fghm9R6QlKqWyIhdbwOAI190SPtG16fPLl/9m6+9/01HwELJvCkHpih/ydA78LilBz7wI9JtBbIeDUveJnmtbvpxcBNWP7Q4pgglis=,iv:eXxa89YVAdSilgeWSMXLMHmfuHAFHFiH/cM7mkzV2kY=,tag:rw5M7IgEaP2Ch2mw++q9Gw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
