apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:FE/+jZJq3uxRpJEQ3LO9+INkYnIfuKoNVl1cVW910pCgYWojYKBu0g==,iv:CCYKcwMY7rcIw/NzRfdimSic76Ta/mRgCCOxvmpvLJE=,tag:eiKAqd0WUy88qNFkRkEfyA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbitHbDdNZDNvT05Lajkr
            amowVGxFblVnM09pNzNlY2JWblRrTHJOMWhRCjFCYjIzZ25DRzViaXhiY1NNQUFj
            TCswaTRjUFlpa293bGdmYm5EbzFoQk0KLS0tIHJOMnBHZDZKWUJ4NURSbXc1Yys2
            Z2wwMkF1emttUThjb0h6WUZxbkdyNWMKASO5mDEw/3V4TA3qXjXprqBJnqbVaEor
            Cxh+eIYz110VTZhtR8QZCSPuDmza5LDRwM3JyzbbspRaqwvlb2bWsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T15:13:44Z"
    mac: ENC[AES256_GCM,data:Xz+L4rmDq56PxXGMIlECs4ASDy4Zt6+vgwbq2W+HuNbxWZ/Lk3SLdf2pYPFtHAaa5xUCvfBn171ITv6fyaDOTWYB3UOnNzxT8FO2/4Ob71f0uf8vUnKRsmH71QAbP/20uGMAmoKl++WAq+6V0c8NmyaASw0zNnYIpQkhsCw9+aI=,iv:5HFMARv6BXljgtqPG/S/JhPbgjVoncxKJudFM0tstzU=,tag:KUG1rqJZBXOMSL/5rAt4BA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
