apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:AlaT5eAwpHkNmI18Mzd/nEq9ws9ac1qji+WZ2IOFZR1T6laSVLKONw==,iv:oQb4r8EsGqWFzSsnjNw6FtjW0QPLWlpFraFxZ/rA/K0=,tag:OzXKO6gjKdL2ewC+NXxqAw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJU2FndzdkcXhuUTlyc3RF
            MUNyWExoaTIzaUpUVi9VQUtSQ1l1WXRrQW1JCmh3UTcwZEtxcVo0L2tiSFRwbHY0
            SWVNUi8rUXFzZWc4WVpXTjRWVDl1d0UKLS0tIHRTK2FtZ3o3Um1PL0g1Z0tjcHZh
            dXA1TjdhaTZoeVh3cDF4T2p5YzlDejQKEjjgfu42JijjPTPl7UrvVMXhcBBo8C2O
            fL5MtzSDcLN+hHn4BRueTdkdY3XKzwj+mnB/BEMPo3APBUhPOiLw3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T23:35:49Z"
    mac: ENC[AES256_GCM,data:loOck/zX34w6W/twRZAwnY5QalDj8LlHX4I96JWAjUZGabwnAbxWqsyaPXDOpVaAGE/8tyWLRAWvrF2XxlwRK98MjdWdN3NLyGg/hYUwfjgCDTndG7Lur8RX8v+uFwuazxFvidpxLBt33JvgxnU1Cg9nHA2VxSK4zT31c/t9vKU=,iv:nBlW9+8NlAJGHqjIR4ukcSbAzcXf1SgMTjYp83Ih6IM=,tag:+lpCik3t9/4gGZLvaxSKDw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
