apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:kuxojb9NthYDkkcxQshFh5XakxokClH8Gx+DGFzoHosEO3iYJwhSUQ==,iv:RQheTnwStrafvWdi03pfNJ/Y3rZD8kYkHwGIlGLmWbM=,tag:/iZN8vZiHUZF33riw3uGhg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSGEvVElPaVhQRVY5U0RX
            RXU3eUJSTnkvZnV2c0lSMGhNV3JjaWxQdjA4CnhOZ1VPbklpRzEyT1dYYVZCdGNh
            cWIvYkk4eDJNRXNaK09UQmtOQ3pheXMKLS0tIFJvQ0d2dUtMaGV5eitqc1oyOVhp
            S0NEc2Z1ZDcwTERrRjErSzZDQzhUU2cK0hbXPz+MdzGovowtTir3VKfoV4rcGJ77
            IbJGQc/VUQVYXsHS9sWvBJTh2Qguy8kdzPK/KvJQa2bECjzA9kULRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T15:38:15Z"
    mac: ENC[AES256_GCM,data:u7ogL7ZNvclrVpVD1rTkcCokLGoEzr1XXZX5H3O7jTt6PBHoXneTb0NYJRcAcie2rLA0SA5aVV2Wj8d7/S58lDw6gvyj1b1Yh66mJXyuGGb4ZVd6pc7Wcv5T1vDBk/cXaRiMrLIFk0zuVZpCEdkRyWJa9UIi5Vy7mkNqeeAyU5U=,iv:MZxSoxo1r6AP6Q+bFr4+qMFc/1QQN6BxmjeDFFpq/IY=,tag:CUMqX6HbQD+5ilkrst2CVQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
