apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:cxIiehZyxA20q+/xZwi+cTyGkFjOlujtiqS+KGucJsXPFGtDzsbnYg==,iv:lE9HrcRr/yDPkBvJJ0cvRLyJ8Q6cgxYWW7vddCIz7Ks=,tag:Fs5uCjuB2ZAju5P/sLkRKA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncjVDOHM2SlNlS1hZTHYx
            K3g1TEM3Z0F6K0JFendCaFdIMTVXNnl5VmhvCno3YlBUTC92b1Q5R210aVJlZFNF
            b2FFeEo5TXVYWVZSa3c1WkdLMmM2bVEKLS0tIEc3RVNEQUFsbC9wTmY4aExJUERI
            b2NqOW1abXpvVmFPZEprWG93WGtwenMKLEK0N6Y3x38kul5NXPBhbPnSzwtaDCeD
            peoVvs1eC7A3JG9feBpsTArfVa/dWzPeL+PRulsQGem8wlfnZXKZOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T23:25:17Z"
    mac: ENC[AES256_GCM,data:6Uh5kVlA3hi7qfzKzHBtigkrbZlT6FLhiabV0yZ6CncjJwLlv1tSTBi5VlRCBYhq9yjTEqT6w/ehXM57JcF2QW3So8hrGqQ8sfK0fWAZNtNiNIsvi1rR4w14qKgiWR6oCB32msYrkWBWhEL79XVCqtR+vLbJtPxJuT3S1OhmNnY=,iv:FO4TQdcH2GUAX9IZUGebRKy5nttC8xszYXiCk71MPe0=,tag:DoD5mmsGoOKUufUbr2s9Tg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
