apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:CAsgQhepj7ANQ4LXMTU+lrbRH1SsDe4QFuFjcr5EnhW2jZbedfZD6Q==,iv:BZkpW+nM2PLDhzo/igOb8RHeHq4LRAML5WYZR5ULADM=,tag:YWggy4Px0zOZ98m/mzoCsA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WmJMT05oQVpHcktSbW9P
            R2xyejRRbjJmcjhPb1pRaDlLODQ2cTFiLzBJClhnR0p6Zjh3WnhhNkVOb2h0b1JX
            eGlJUzA2N1NHRTcvMTJjSnVuRjQxcG8KLS0tIDBpUmI1c3BuWjJsNDdzVHdNY0Qz
            dWpOVVNHVFRtK2svUHl4M2FDYVg2NTAKuYuiYpJhGjhDWOXLbSkZ7n9ACcK7AEko
            hFv0HtVuS2ApJrlXFVb/MDILxWJ/f8suMiosxjBtBJgiiJ/IC21xtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T18:17:32Z"
    mac: ENC[AES256_GCM,data:mGjtKKRhqwIEpMICWha4pQ85Nz/aGfgSKVet9TJnf/zEyj3iP67CSb+IsUMALVkldKlTy43pwk668gVqni2BfFv0fsEIh1CAWwyOE4HnJlLT2QdiuWYfEjWhjn5hOiVXOQLKBjdCse4blg5ZNdGDpM+jHwnscchDyQRvB3tey0M=,iv:Xd7RzTPRU2dokr5oVW2xzC/QIDLNwYEo/y0WHvjsR/0=,tag:Fdr1a3kWE5CZsj+KDVOe0A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
