apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:sPWVeOsxyJ0nbAGiXDslBKoF2muxMB5ueRO7qKej1dsWNz+a6hxfpw==,iv:aXPChm5fXQybZGaM6lZQDgVlqTtbtC42YPW0m0qxvhg=,tag:70IASfhnNerRU/A9rWj3lA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNUsxS0ZiVEJCVFJ2VmZs
            Y3JZMEV4cXErM0VsMXZqbVdhK0RYdVFvV0hZCkp1VGdkYU1ZV0FUak5rVE45Sldj
            WXJuSGduOTd0a2tVekdqeXh0Z0pqWW8KLS0tIGp4MjNOY1JCbHpaLzRoNlZ5UjN3
            YUJvYUg2Qk5yc2FCMUozRTFzSTV1MEEKvmWtnBjcFOkAX5d7+ppBSz8o8BklMX3G
            XYHUfOQ6ReHUWtKNHvARPr+9vmpgpeqak2Nbkfj0WdRYzkl79bCGZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T09:38:00Z"
    mac: ENC[AES256_GCM,data:npyC7+5hb8NTumix7IfIN9HBM5GIho8HSvA+neFPzw7BS2CxNxeA2doDp5z/5y4qRHLvu3/A8TAuv3SB1CZkfvUVzgPqy/LUZ/B93U2SYvMIiseV9epX8cIKPwZQsBi2xv7zz9bjln2zPl12k7CzJjzjD5L3L3jK8MbmaoCJ+wY=,iv:Wg9ZhOhH8tSmcgbUgFGjhUbOlbJWYg9bPN7SURKl2wI=,tag:LYKsvbSNGYWxrAO+/MogQw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
