apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:SKNRjLNU+f1Izcc9gnc5ywSnJamOnoxWaz68tEEv2QZSTYpF80vLMd1AftPBaFHlS4vgHauvit3dH+SNvKinbte4+YXx9zinqlWP0SjX8kYlLBcmRkX++su1f9ve8kfm4Qt+oNn3lFADpm8MgHOR/9AHVGRf1yOtffjaVtJbd2l6nnU1bZDrMTv9dzdCqwOse3kbnAgJkjkMzu1UMv7BcAmh60Lzs5Nv57mAH5Uj3h38E65CQTwiBg7t4WFNDpGZWunlFkVoVncg252imkqgUkH1vFf/PhimQFNL/GRH6MTFrjkp4X07MAcbLP2Lct1wTbGPNNPAW5+YkxerkD7GBtRcuXj/frDqL62RLNzH6EY+P9WjcxycrjsQtLdviyoy,iv:5pxbvVbwNASL11GvseGouwZwP7VYOOgBF5nYqGywF1s=,tag:cL1OtozVQ8Pf58TBNqJWmQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:5zgayP8X2Wq5F2/jkZJhIu3j6aulRipZ13JLcoK0gDvvuhgADogSGDuT+jApREHklWTuKhULhBTHba1exIjdhAMoX0pWqUsP+s10CDonOR+Yc3BBGyJd+HRcmbH1Ybce0qtWnvl0dOuRBmxgNTIn+YHJzL98GTby/GOJjQo6nGz8wYy1mEq481dOl/TwcRF3STKV0XJuRHzL2fJ5AfMLjDtGzJBd723VDmo4Uqt3CxutWZT9VBniwJiurxL7kFdSWvzj3IHQ/q+TFMXJeg==,iv:Xgoyf/Pw1JNXgwH/LkqaXFuAiRahlvtyNLnhaZQoZwo=,tag:MOdPRF9En8I970yungavQw==,type:str]
    known_hosts: ENC[AES256_GCM,data:w+qvX2Szn32P9cWAIiibXQQKbbyM4g6iHJI8QK4ALsAL3Hq738cxsxvgBFT9mzJ4n+8+Ewta3AQ8Q988mKib1y9kT6Kj/O4HGCDsNIZU/E9b9NZGD5SgpN5N+ZEyjriHyjP4Cq55eeiURHP25xea30OxXzM7hHmgK5lJqBtpUxa03nmgh78ddX0HhO3Lk4pMJ08N33jjMmHUgRs5VQ5J6JjZ/TR0d9d6FTkR,iv:itaqAnTr1VYAYMQFNCHC6ydjxND5Aav4PrdIi4XCXnU=,tag:LQwDdvOvidVnqkMQMCa2ig==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TTdFVmFKVDV2emtwdUNs
            NWZQOHFVNExZT2VZNkVsdzNqYmcvMnNRZWxNCkpCaFV2Qi9zYXJTZ0JzTkgyNTZ4
            Nm9HdlVFYzRYVDMrRHdvMm1qSU54d0EKLS0tIEEvZGdrVUozUUFsVkJrU2p6czZC
            R3pOaWNRZTBQdE1TcDJCRzRXSDZtdUkKgv3d9Jv5OWJAXkrmzNjjQU4Lx4JSz7kg
            ZndrSkv6WkrJgK784Cedto+GDmcHmNJhhUcKuKvNHrmWjyEtJeXhrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T23:33:32Z"
    mac: ENC[AES256_GCM,data:PegoqGLP01Jh7IuZjSzQ9EDH5wLxeKQj3+FxncFyZBlJ2UbVANMxBsKc+WdOQJZrQBtxyHdnYARPdkBxLcsPDhPTPlBlMKqDouTEism6fScB/WmnwEPEP0KYWS3VdBkll4Aw8KwyMyJFnMiOMOOclTkcvaLgvkEVmmFE9Sie748=,iv:aheUvkmam2aAzQ11FqVoKh6j6LU/T6e7Ih+lOo9+IWo=,tag:3XUlluxG9f6NQHEOD0CCWg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
