apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:OL5FB5Rw9cLgTsRqsW/wvq4vVEHjSWYeM3jd7ylT2AOM7mAJ7Dyze8oj8kIBv7cu7fI2zTUyKGo5D3UrVLef7rnP+CsmuInyOSEvqs9g2DkP4GP91ZGr/iDSjS460KKcU1hMpRgNSR9so/OAOSdMs+W3MmUnm6x3VS4BYWUA6m5+FtTTFN0x69LxgckBIPF1IEjSJfDL58kaf+rEMWqoAzG1rEZIT2w7daWQKrzxCECOxmzUI8xaWAuhedES5WoLEh7/ZF9xr9cnip4M8tQDsB7H26lRSxLyWjrXxeC/cm038FwAgJ2l5WvzxVcPqukj4oK2mpTzgBVZVj2sW5ecudds0NNtxr8kVn/xe7yZly1p2mncRHXEH6cF394A3Dfj,iv:OR8SOFBIPL5jHMl83sHYVJ18nlyZGEov04fYVUJjl4M=,tag:JMwHI9j1DGNjPfmCdIUstg==,type:str]
    identity.pub: ENC[AES256_GCM,data:demNfPSbJDU2dd71gwdZGZdQMzEyeNe+ykyqSgjFLNGv1rEZwV/BjknUA9aUr21WwNvED/ANCd3WNG8b4b++0V8K8wAq4CcM/8p7gVptXYJGhRuEervWWfJHZ8dD98ECxVgxolD75k9dn4MBeAO9SMnSTcXeHN0tSi2uPI8W9UEXg3WXFuICnRucN3PAiSjBd1lfTfpToNeNbe0ExsUFimNEOJUYbDWIzPAqI1xMSmasB+YHIK/nApUm8JvFIP74l8LMCCgAlJypKzFyOQ==,iv:aGTSa05BxgCZKXSMNLTNFwV+PS/EQj9WXQ+D4mVSKDk=,tag:RvfUbKizL2DnvlFP9PqBUw==,type:str]
    known_hosts: ENC[AES256_GCM,data:74Yk6IYvrg+wyTv9ZbpwqykOYz52IPq/OQjdMsFFhdCbEhXceO+1upVBNvEYzKGA1gqtB8weHj9DioeYyLuDfimDPa//VnaEFnfK0H/IAla4hFvDTlxDbDVtVCQFVJkG1no1/r/Z2/eY12BlXT2tS+ZKVbejynB9yn4p5m+1+wyfrAL69vx0f4rlAMfPVkUBiKhYOHcOTjhnmdEPW5GGMu/ooEHuUZRrXcnQ,iv:2wJ0Zfzsv8d6zYrsUYvk8FGHKS6eivWbICfPhKWY5+I=,tag:85PtISgjYLalzy2wmdD/+g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUElXNFByNjhIS0RxNUww
            SnovNk56NlZ4b3lLVTMzOVQ3VkVwNlNwblRnCi9BMTkyWTZRUitwWHJRcmZSaU5w
            MFdSc2xDZVhvU2diaUp3OEo3YTZmVEkKLS0tIFJWVkt3dmVzUzlQV21PejJJMy9q
            VkFzRHNFL3A3d2I3YXhlT3Y3SFIrS1kKO9f7qWHSaZH6flmeDV4x7RekfO5di1Ia
            bu9Ki4NxsA4dBF0RumWatv9V51gWYaOsK2MooeTZ/tM+ASHuUvY+Fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T23:25:17Z"
    mac: ENC[AES256_GCM,data:8+qIEGEGLdzkINCrfxBXlly0GCLCO0GqQKX5vcHtq8ZuhTMT7CMpXjktiNXoeDN0ka6h80eFvWsftuWHjB9qMcEhGu4676aZ35cGrYL3rOncva2XvsjsaMxSG4FWZkTcJG/zaHUuhBuW0VOWqx8Rbyw8woN6lgw6qSvYdw+ssJw=,iv:on4raXn8bQ3uD6szbkMOH7mrNoCcaSMzr5cLRfntoTI=,tag:JbpnSXRP5XXsBlfZ3uXOVw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
