apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jHaZnpySi85tYrhVaacDNq0Y7BNPCpnGYXuUA3QY5zEOxHO2GeT5bFn57aSVmrJq74oVAL9UQr8vCB7iDRv/7oRcxMr/O+H3Qm64MoUvzBY3W79x3NVEz6TS1Kk+P8eYibAUgjIXlMCtu69LJTp+T82bhtuIXP/BOjTRlQSkxD7t/CB2AZL1RYjLGwP2brc6drRytKGHayIl/i6+BCHkfOJH9k2oHteM/+mglk8hcxsZN4/7P8Q5/vqxRkbfb5Cki6T5rRjlZEY/am/ALC9vMeg259F4zygYx3lude99GXy2yzVGH4ZkkJMcb4IuTK+rFmj4/qXMRPE1URbS9kH5rhyIK64D/Ej2UtTz9BVcnMR2ZedGNGpyQCxduRqdOnaS,iv:5vsc3dYPX70IKobfo3V1oWlXOR4Tl5vZFEaJJPavej4=,tag:kaud8MiZGKlzMorBC12Zzw==,type:str]
    identity.pub: ENC[AES256_GCM,data:2Nb+LCWAGrCrLhdmXLNEUXpJ31I/4Fp4f/7gej1qBuM7dERczgFDY8yCnXbyx9/7w9K2dtYbOujvek1Bly2g4JFmLFS0HyVHyXEjC7xunDHMMr821xZale/RxriJ20Gm+IJ0vlooItaj1WCi3cQkWk5h2iv63tSU4zNEC3DY2OKc0SpnKIpxtMnwailN38hsdrV0JFQIh3tGtdtjKrcgVOIpuCTO6Wj/D1NUaVzoV1v+I3SNJp7GpvwQVzUVncxNqvyFkHZDwdnmUg8fbQ==,iv:6ZTWIyJPkOEjLVKKA1vKoLWXEq7t+9HnwlrJ79jl5cU=,tag:7Zl9E4p4VVmKES3m5uc0Vg==,type:str]
    known_hosts: ENC[AES256_GCM,data:9ouqhS3g+Ioih+bdPa9aFsr10Etsrh8R+Omwy5oQXCrzT3IENcQ6+5BrIxM5NXeivKRCKwBTBrS4C2A0xRWoFmJAmI+LetTdSu91WgxBbQUHf2Zscn5yY1+q280NFZEZTiR1mvB3iLVXQrd8AySx01ahe4+QO8fYUS28tmPJJ+S7BGfA7qLXFUy+eOgsw2vR4ooTb7XY3fQeOlQXw0lB/k2xCWGewR9YfhTW,iv:oMYQAhMynk5w4J2E4DNRzZPyN75NDEVC3GJmJrw2Rp0=,tag:erg0Llg7witI7MTGU++WRA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeWR4V1V4d0UvWk5XcU9W
            L0w3T3RBNGkvWEpja0hhcFNxZmZpbU00OWlrCkw4a2Y3QjRrcWplbDZZNFl1VjlU
            RzVXYVhIZ2VuSG1CTU9tS0xEWWdEc0UKLS0tIEVzUEEyeGpRYk9HTWgveTd0WTVL
            T0pHWlZ4NCt0UUJMK2RmRVpScUZoancKNpSl9MuFE2xhMAbWcwTQFFkfOnpp6I+H
            8w9Y+vdzc/EOx85xPYHw3izJRMvzSp0j3iIKVnFgLDXUzKI2JfohZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T13:06:53Z"
    mac: ENC[AES256_GCM,data:r/AUMFNUknZfey0EnVAwA6iKpKJKAaHjPpzYdJBn3hn/P1i3cgacxUhTVaapGfm7CMcGb9k8b14pCOWTF/oggbC8JC92f9ZMKukDXOL5DtbN0seofq9h/QpVQ9SO+vkcXp8B3f/eghzsfUGkRpXq7t3nHZ4tK9HKZ0/yVlAFBHU=,iv:eeKUWh+S2gtRFQINuWp7NAL8xqcl8JcDYkZY53dK/iA=,tag:TrOBbBQMBAZHNNOTE19vEQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
