apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:eW8tAUqTHv8IhuAsV3OhbCjvN0EvzUQb3kBHJdlUlZVGLK/UvA/LTGIiWUm+ZgjnCBGXMei5FsMhNi/5V/EkCYA73NO+dS0De63mwGTPGgHTF4Y+QMgL0a/Yx2Ro0Muzd6dM+bPwd1xYDvNZHWIJF4qrjKgyHlZdTMIHRG7K2CcZwJuW1xTElomBDCdXwoZggh+lGQ3hB98oLdIxk/mmHQE3so1L0nOpBXTOyqHJu9B5LK6eTS+Tn/jUSelTJ+xfS9kSCgfIJPH7GKN7gc1z0eUEImnEVxHlH4VzygHxYH4ENnVZ6PvoH/Z0fYAummzjSCVpLOUdpXZ8OQnnyuCgnpsHt3W4Lz+a3VTfiQsYcEF7XSBwEBirAQfTKMBuQK4V,iv:1wR/4I3HByY3QdQ5uQP8dSl/PMKQGVSmL2nqjRDIrXo=,tag:qB0EwFRZ+VTMjuDFtxoeDA==,type:str]
    identity.pub: ENC[AES256_GCM,data:ek7ENyOKChRBNiU/KDLrU5xiTJ4EQFDx+lwT18zS3u20zdM/Ci4MCGbwL8nD88ZVZdB0ygjSqGi8xBVKw3XIsD7sS6sgkjM/sUyZpv1BeBqUeEsie4AcHktiyUuYTY+LDXqI1oWRjrxlIbmhlyh2W27WIViBHbLrNZwKAl47riKeCrEirlVNgCu6115fOg97nrT4IAn9i7MKu80ea3IOc/0ncyV7zPTZdzGWJuGCu1b856knY7FFjBBzopzAiftfyckL1qUQLFWyiRmI4g==,iv:pwrO+6AG1ozAt/klJzBBh5n5RZ562IGAMjN8IUQWATs=,tag:FG9SIUi2tCVOj/B9RprMtg==,type:str]
    known_hosts: ENC[AES256_GCM,data:jqZB6oFz5CTCjQRMxQ8tsoylZGFMyBNpzgVW/xi87DJKdveAnIRGwPkXNqr0UMvXkslk9AbibyRf5EROsJlwLe9FmMnffwRcAl6gRHDis5cX1YV2nQygbyQrUCDcU6s/Vqloj5BxwxYLSiSF0OaNbXJVPkMyfx1c+HLTarSaB7HU4+3/hF0E+DATONMJpc5IVfGbWkgDKIX9GrkODxjT+PXZTFxflsQee05A,iv:Xuinqj4AQFX+Q2QhZnb3mCdFRRAxuD3jqPCk2gVC9QA=,tag:yCl5sI82SAHgvTsBZUzdgQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZVNYNzZIUlVIY1Jvd1RW
            MmZYMWxaUFphdEZFU1VTbEpwbjlSRFI1MlVnCkpZei9XeERIRk1wNGtUaG1NUURm
            TktEbUc4QWs2ckh0cWpiQ1Z1a3MxaVEKLS0tIHBjV1hMTnduOGgxL1JNYUVnT3VM
            SUdaNnRDTjh5YVoyR0h1OXhoOTNLdEEKMUc+iT5GAY4j/ljzBat0ZQtERPNXIbf+
            NDkiONHDww8cy8XVCuWlqZM7IEPbUMKdx0J1fnfdbiCf754WLe65WQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T08:08:20Z"
    mac: ENC[AES256_GCM,data:Lm5Bg98BIl+UwqvYepMiqbC8L+dJbBbjWzSG6An2kVyYG9PBXzkGuAG29DT3DfIYeYahJDtukO1HZ56UO+c95TY76tYYby1GAmakv07ua3OvOyP1vMiQX6/Cx8q8pu78ry0sawLIywDCmkcBVLvUfm7KYkwSHg9TkeAUl07O068=,iv:jZPuVPZg9vx6848qPbN2HKZGnh9sPAYlIXKgaNoy42s=,tag:S1a52KKkgehYtAARj+yKJw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
