apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:+d82ELRhEi2HM6D3ONZ0er2sG1z4fQWxOxJlRMeOgS5xK93NSVJGRhW2TKHkm/hZRcLeK6Q9Ldfb/zzybiM3t4NpdxngNYrkQv21um7MR/cyGD4Q3aVKf0NvpYIz6ymcd47bBajVjK1T+Fp+YsO7k+c/aj7A9/ou6HGrLDR+v/KGaVXcSlsPDwLVuivK0+A+68ND1LBXvDDb6hiJVIO7zS/tEi5mch7P9DDnEtN2rmgfeeickSneyILbMzaDE253SDrX0cZM1HpbBmd//xB/hqdK0yePISIqrzBNYuIMMNFu63Ly4z7l+2lpm5ZGXKbNscGb9xOWS3fIZWt57Y3HaNaMJXsdV2r0B7QrV15hQGUcCfi7a9q+sQgRv187F2KF,iv:N1Au9Th5oLxvGNmSgnB8QrkgLMYmNZw2zJYh/25TmNY=,tag:zW7KugdLT5Kz852vTp2gHA==,type:str]
    identity.pub: ENC[AES256_GCM,data:aEtsHDTYNEpsLjzHTniMZXg6AKLq4cTOfHtu53PFLtPnQxZKFzXENsKoNj41msCXW2QfBHOoElN4Sc4DrP5URqv8ae6hFwqhUQ1R8nhQXENR0UrzRDMoXr92BAne0jKOqQhzt35w2FNgTJ11YG8scwZoTmDiiX1ti2tSQaeuXUYnwUcGnWJF6V2fAEBeAUD06FulFXtlLzDdyfFdydlAqY4FGjN12cIP+c2RjjjFeV/obeVNMd72p13QfFMlgSKC0JIY3QDvEk9kAWMQSw==,iv:i30Nntweq55X+4pJOVshOo0BSIAPBZRzGPOnrrzk41I=,tag:ikbxe5zLkvkGd68R2lchMg==,type:str]
    known_hosts: ENC[AES256_GCM,data:AdzL7ZZjA3iHYi23fkask2Sxi9bxThGIHkh78W4oJA4SxUu8j24gdJvbgFMJ4wLNL9id7Gr5cwvoR6Fo57qOwyVALAE8KbpqkVXj2nrLIkgw8DlQB/Kn48u+pyaCHmExL6mvqi1SP11EiiEdWAcgheX8RDnmO2ZqYKR5+z81FUNMGzGQYtQqcZtVRrwpzvbGHf39seUGGS7t/TfzqUrO32B7oYrhqglgBLHW,iv:o/ll+efu84tbQ0uOuMMrbAmIv5sE9mXLv8MH5GUOdLQ=,tag:K6yumj7TGjMMeeR7rITyVg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcnBWTmZYV2FNcVNlR2lj
            czNsYTVXOGZMd0pIWjZIQU95aGM4VDVjVzNJCjNFUko5NkNQdHFVcGc0eTRLcVp3
            Q2VJTUFVNlllRzZhNkZyMVM3cWhXeGMKLS0tIHc0aHJRTnd4dEM5eXYwN2s1Y3Mr
            TittdkdzQk1xRkFXWldmMDQ5OXN3V00K8nQieqMoKIS85frlMivRT9TnJxC63rpy
            cjll5KzjmpapRDw1e+WULXlODA/ARqCCe51c9iBiakjMgeE7sCSMdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T15:22:33Z"
    mac: ENC[AES256_GCM,data:URtOQCBN95nFfrhbhtKyiiROeIxdjtk25b/VIlVYqtakN1rgLXKjc7AHW2qKFFN1rvlAT8ZYXx+Xs6oaChG6xyhNPbTVcUXkNKiWHpV/eqwMHj+SoANmjl6lThGjq2DPGVheA0S3Yvpiv2ckD3Mt1YRJ7z0KR8rYU4EnmMDGRbE=,iv:nhOW5bp9UiNtkd0Su7dbjeOZt9/NTgn0jBjkirYwMaE=,tag:OJMa/ODNijrbgPk5WO2AEg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
