apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5e30aIhoUne9ka9owQKE2iuYPVaVwVNaqQTETqGGiSc/yssKnIayqDF/DzC5kFCNaoVcMXjziaO5M1MLKKclLVR43KpZohd596QYosvYPva9+Q7kYtN/72ivcUjfV+BIsQJ3rD8gAWm6apFO9dGI3glMlt+skruW7izUgIRg+dSORNYLVkfejKeivzhBdKcmJ0XqZHX+aBw9VLaBuDU3/qtOAFtyp1X6eNp2fs4pkMrvqhci8JOu2CZe2b4zF0jYOZJSE39OF5NQFnCPE2FR7MHreFsxQkJpe2a0ATeIRcQzrz7twi5u7Hdir0HYSFMWF8xGzfBM7C9l0xYDorv7hQC5dTiknL808LNikbhniCfs2TjVhgWl9VCzDwc3DXmK,iv:eunb2Gdm+AMlmV5LXeJow4ilK4hGF5c6eV1XlYNwf/E=,tag:MUBP2qDZmv7KR6waqHy1xA==,type:str]
    identity.pub: ENC[AES256_GCM,data:nhPNDRC0uOXmjJEcZeWZ6Vz0Yy9/FBX8oy2eX9G7x8r4/20yM+LeiaBE7zINzAiKM6bI73ijYSAxwC52iPxbEV3a8xLT58Roeqn4qz9y6RCErQeN/JCrcjauXtGwHZfGXtvpiZOIU0WTozCMFUwIBlFbYBxMV9zHEcE1Q4F8X5KCtXHN3iiLR/gOkAHQVxvUGqXdB5ZpQCcpABIWTj1C8zH1lpkbFzS82G4YqB6h1L7GG9pfoJI2Aws4h2Qh8vbBFjA5WM38WHCZBXDqZA==,iv:lJCBITpYcQYx/yZTX7VakcG8FvE1th56Y2Cf6ItCHRQ=,tag:YZBsyGpmyTARxBKmLDTOCQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:6L/qlXyrIp1h+PqPybEpuzcPKnA7sBbHMFxhbllsQXta+7jFyX1GYpwlicLsKMH8tUOjgekWr0s5Js4olK/DwhlpPjEEBHy/YWdeNFAn4NyJ970TsAUmZG1wcmgrsRxQzF/X/mzRrZQzAtcmX+256N0dDn27SIqu87L4r8nPEbW7VvaLPnH8tsxQ0mx6lJFGKzH3Ie/NUMw27XY88FIMa+AOoAMGZ0SFsoAX,iv:R5umg4ol1dEAgCBu9MEUqUkCqReQ5JHWNx3mAEzcKYU=,tag:XOFmnWh2DSRNORQXRNujuA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVnFQNVM0cmkzazlZaWRj
            c1FqcDZsWm1qNjFpSHV5bzlZNnZLeUNYQ1JRCndBakdLTWx6TDQxOC9uN21SczR6
            TFMxU2JGcWpSOEl4aW5jVm5ReURPQkEKLS0tIEpreEFIRkRZaHVXcnJVY1gyeENk
            UDYzQjMwTk9EWG9QT0ovSGRoUHAveEUKKPa3t3ugcU7nyMdsv9V5gWR6FvGvE1ra
            6cPsMePPzxMO0slndd/iTyt2BpqkVPO5LAC2Cgq/QToG6Lz94VcCpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T19:04:19Z"
    mac: ENC[AES256_GCM,data:Qg2XVJ7KN1JfF7uHhoNePfUNcA5IYpzYoZ2lNYprjdUPnYp6Vb03DnorG2q54f6eHobA4jQBVSEFQ1VEipc1iUi7dqaJs4NVeEZx1LOeiwrox3umNA9w7W8BvekFD7uIyEYBZlfra9SQcRvIBM2DVcqY3ccTPOGg1grHGz8HLFM=,iv:jB1wYqset8n3o7hoG10moPFKmSZ4yXz8U49WjlxbkW4=,tag:ECsjdsu7K2Kx9/wc0R321Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
