apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ZXwrF1LEUyKyqwQZbuTuMUuVFJZvH8QVO/thvu8avvP+BN6r7pqFtqZphe0cOqFA6PLPW07WeKrpoor6z1w7Sa3HrJRcgMGQsylGDoHFVMg0/qq/nC+fHgsSdbwGOjEkXpewU86ZJFBmTGJSX9ryotcTR+v0cYt5jsj5ab0Y4nzXHoAp5f2jUJa4PWbZ+kDXTKy/AjPbi0R1XqcpMJe+/Cgr8wizJ64YlFRemSQOY6IldT5OJm7goWgdbXKiPIOowrGYiqggrfVmZ32kPI+/P5xzwfbUTLWzAUN2+39db/v2DSevAfrOhM/rYf7/IF4cZB7Ni1AYBSMoMLpYCyZWJWW2nkWpcZz24fSzO3bXppynDRhk6hOptFPh6Bh4+Dnb,iv:lp3LrawevBLRfLnZnDSlq1/mWLAMo7W/gpPltfoSrw4=,tag:foXEaMdZZfnpAkeRDJ3poQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:EAU5FK/X4SH4X6gYvtmyGayWSF83KBVWGdv2qx5Vuo1GsGnoX6s+uv21gc1i17mNSPHaaTB6z6sX80u3ZbDTpy/gbWjPikr8BDD8d4g2bhUUvLHstTVfdZLU4d5LswqIR2KRCvbahLReXS3KhEdXHnwkXp36dlRIHGdd6maApgREWZv3uoj48E96BvWias9gY78FxBe5k20cAQws5vWuINEWjyFBQTJAtB/nWTYc0nu9DafBSyUWMQS9JS11b/P06yvpfESo32X5NqFqCQ==,iv:xEwgfIhyfoJMSuGs+PSWQCCmbzi7SKj7sxO3Kdm3RH0=,tag:v7JgqaI7kGXzB6BBXAmbtQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:PbemwIDVKzZRQdyMb0BBefAEySyIiQ5ycmYMlFG4pDnw4JYml7viuS55qnozjKJoiIR2dJ5sC7GrfB7kGfnf7kLVk/w3t7qiz4OtmBhBMgfRTUxpVi9QsXtS73krHO9md3hMoULlKoyuXHUqOI2CKj8VCSXbCHyIlzHE/rTACKxtd/BC6vPTo1AybQ76RTzP0NAVTrHKNDMKtpp8/pydP5MaIiHFnpSHD7HQ,iv:fFIZqVg7a1VH7IUcu5C5yjUluGWwTBYpgaNp7ECzU7w=,tag:hp549h3oxiFNZwjeCppWPQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcVI0Q2pzSHY5eElaSHk2
            cDh2c2JBQ0RrV0pCQ0tLeHh5MUhOanNnd2dvCjFUTGdsbUFKbVV2WTE3UkFaa3hE
            RncwQ016NWVodzRRRW9UaUJLSEMwam8KLS0tIDlmcmFxQ1BTU0J5UVV5K2ZTaW9o
            bXB4NThBSDk2cG9aMXpXRXdBQUVBWVkKYX3Oz6/EL7EP5XtNrkyrlQBqkUwxsxOg
            Ty4QwOTPzN36O3hNhEwda01NxmAt82yuwZ1A8AQK8vBXk5UfztgmrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T21:08:08Z"
    mac: ENC[AES256_GCM,data:CfLod+0m+19lLhV/nGEMPhp301B0E/j1oaMT/Ji7q58QVtOFe5UB6mluDVtS2t7xGOmgnqJzKB50Ho4UEtGgsEd5+t778K9+pzcYl4psXCEl3R/VYMyKxFb/x5KGSQfdR+p+ekZJzdMXsB4DUMvbgW9Le74fPY5z9sVUDzxjaX0=,iv:f6KyqDG45dfy3S9oMTu7QkgpZWj54bgBMoaLM/yS3KY=,tag:UmIuyMHPzHNtqZ4iunKKsg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
