apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:7OzCaBiAbuS5DyVwxd5r0ZxTCqj/KdLhjIhYqLCjMaxXu0MGAwGStYR1MKmWNiNJsip3DcMmJV3itctzGSkPIBiGE7FEzsjQF4pOkvjPcn28X9SCvOyjZcNEUISpRP9SJ7NY5QNTW1tYudjd18a9M0Pqmc+eVSl00K0MBkHYZZvXerxtV/frVgDwg2Ev80Na2pVuMIgkd5X5nDbBzkasZ6j9U4ofvccaKcyuRLNHhxiSlLpVYpfuLkUGnl4V830tVppmqtAmCRYtU5ZNo//kXl7S4hBAbSc1BOAR4AJxjtFPI7lwHwp7enpe+YqGVq7DCVhDlpLQGuDicSmBOoSSi8j8ukv+6lOcyR7jQ5ki2ePubka2+1bggCa13rAj1FY6,iv:ll0lpj1seEVKVZEhsOePlEtmUAxZqWLRyRqcXBfIkMc=,tag:6Le70CVjw2a18OEF6XWnVQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:iJczJ+QJnazIjsBiL7KYD4jvsmnAfe/n8RrJ3MO9aB6757PqgceN4ncEha7nfrZpni/GzOp6TlswkgJcg8COggK1ozyF6eDm2gvGfo/kPdNMLVYc1lVENc9iizIE0Pm7IqY2kUkpx5QZpvJEgUp3p2X9vlulih4UwoYGpW6qOJdPJNx3ViG/lk9w1yafcdO/4ImAOOocNFwJrMrldKkfiujOBiblafXZevO8xq7ZKxCYTWd8qPGhm/OLXeIqjEA2ZmE6wKc2V3aHH+RQ5w==,iv:nVe0zvc/YOwPazgf+CPAdhm7Qb5fl1ppx25Adb3AWKU=,tag:DFW5/x7B1S1xIc3je29/kA==,type:str]
    known_hosts: ENC[AES256_GCM,data:DSahNXYLOIKZArZO3dfBl1dIwxOYBhJlCo+MOyicG9g0QDMKTTwlhX6qIJm7nLTNAklWh0a3pYgVND+UfoLhmFkuhNElI+Wiwf3X8puQBY8sZsEpUfrKF7Ackm2Ylpq+TedmU41+vnTXCfNWEIufY2b55ImBMl7UK9RGl46Mf6FhJxxdZS89kop7yu90wGoab4JGKOF54pt5HawnLnRgTT3t3ajnJ7QlOOOR,iv:4e+xTZk4JxUIbRm4FK8MWIqVx964W/3JaEg0wxaUP6A=,tag:sO43xjHfNJLgTxHCag7g9g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MUl6Mk1ISmJYNU81K1VV
            cjNTRWNIVUxhZFV4VjlNaWJZN05qZTkxQ0RNCjdZQ2VkRisydm93NmRNZDl6emwr
            eEpKVjZIM2oySHdTWkhjQjQwa1VXb0EKLS0tIHJPRmVYOUoxbmVoVWhxcHlXa2lS
            dVNuU3FoVnMxczArT2NlaGE5VmQ2MzAKEg38mECvdjRXFULHOgPMQKHuGF/uT8Ak
            ldQ+8yMzqyDx+s+r2ZmNURv+qjRo6tz8cjHfO5+zgJ+BU95LxRrp/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T15:12:51Z"
    mac: ENC[AES256_GCM,data:Q0NQa9UjV1fxbjwoJGUCeD9XpJRByGPIvf46w6mZcDaUwqGXkmEqXDvrau4rsPVlvSwPCmDR7aTgKdS9lQHkC+0iYRPLu8Pu4WiuwTjnzi1vX/iFEI3Tx3o8aEJc57Do7h5ciNQxQGnscwuWji+4SWwPTva2CZAlh7jnsqTnApE=,iv:Abkqp/5qPLtrmvKhV1KewPLW/EZzMuyLKOgBpQAI9+0=,tag:txMTACtLd0wyV6M6ireZEw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
