apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:r0T3y1rVnyhZS3YKILMKhMZOP/FkatgRhMlfs+lawG0NvjergCyi6rmE7yPtCD8XdNxfe+QcmCOi6YzpdPS771L1+VrKPrnCbVNwAEjOXOy7SH9lQ1FmgTaXbVuvg7wsTDrJsEdpQpbE7VJOJbIPVeoP3HJ+4GLY33qDPCCzIB0zINmxFZHAHZ1JBwK0+BMiUFBrBqlANyDyw+DG5ynQn1gdCNF3ZSVzI81JTyyOuZGH9cOWch6aHBIf2lVVkXNs4LeapP8NzEeTIESMNXoiWDNZ5WwIy+FgtvwHQJZZMlBJ+r6fEyjSYhKH5iUdQnxguK1smNO8a8c6RAKM3xWY37yQYhz9GlvT25DoLnu6057h9Ibqhxso/sItjCkgQPFk,iv:qApWkhCMvcbZUwyPZKCmToEAQo6f//gvnxifOJPvLtM=,tag:m2DaXO2yiHXCOx5ZGMGVMw==,type:str]
    identity.pub: ENC[AES256_GCM,data:ondlS+f8oivNtjeJn+9a5r8iB/2pnyGb/buJ3UjjpCD6S/JtAmVxcGUh5+GqNuRqe63fUBe5N6Uswxr0XQcdqfSlq2T+vlyAphCV9RhfspsktIMKsvDP4rc4QhTXSQWVONk6pQ0mQw/3zA1gJVaLJfw7aVRnQx1vcsnQUVm7V1GNAHr3rgHP4yEojOuOlfBcvI+kkdX4p0QA7H9PNH+KrzqxZ3wFLW8UAvHZgWqhtWFJc24qveE3umE6OdXYJHkzrnKSHOnquKEikgQLIg==,iv:j+VZIHLlBR79ISifBqTuCEiisnhWv8blt05/v3rj90c=,tag:bR2PtZgBjzPp6RNE24grDA==,type:str]
    known_hosts: ENC[AES256_GCM,data:GqD8GvaLsP2faGZn5Emd2XWhiz7bYKytbQME3GZacqIki4aV1JMlbDXtTPsC0/1IjDSmXFt3QWQQAXWZKuU1wf7pkP8D+3Qn4jPfmS6qU9H2EGXyYbUUfDxxb4rK5RyRzXBzokfiyBvbdnBROR5Hdoh4XhOjc3zhxKC3T6nrDZBdxD6eeRP0jyur2hR6gMolWt/RJ1vOUkx4jz15ijp5lx4a99rlWUeZh455,iv:lK4OcVT8JUjLmU/iYPwo9w2oeNzJLX/gYwXUonDCKvw=,tag:M3NeGjHnnjFOmB+6yWVNzQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4K29oaVBrYVljc0J3TWpw
            NkpscVpsM2pKNVBMUjlTSTNhcFZKSXI3NkJzClkxbitsTlBNNGR6QU9tKzl6L3ZX
            Q0ZneVZwWTZRQjZGOGdtc29sbXdGZnMKLS0tIGJTYWVUR3RMKzBxK25ZcHJEQm9D
            WFk0RVlyeVlQelM0MklYRzJuZGxjMVkKu0oLrbzK5aq28cBtVH0uDkINnUnRLGkG
            yMAR6rOnKTP9vxcba/wwwJVcucznTOKbmlDkGlvNo6sFZdU3R7gLhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T21:13:06Z"
    mac: ENC[AES256_GCM,data:FzUl9xkiOvtRiOs1CyXpjbbbqmy00SYoUMO+MWoJsU7jyTAWE9zyztl9ggkO5+mbONpzEne0sU/pH7RisIn6KXygw8LgN8z6B7ZmfNL7HdYTOmss7jOkiiHoRDXL/h5DjKO0lsUfYCtYwSaJU9mkhCeDa0OnWV+zU7leuXCCXbQ=,iv:2ddV+RPXC+WLuC20nLVGbUXYNYedC4F4f4EutGL8EA8=,tag:iteByMgeRSMc0uQg8GWVDA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
