apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4d5im9P/3T4RhPZKG79h4zDSEWgGTFexA2cibkbJOLqRmuwUKfCvWxalCZdC48SQhPt15Hf9mFLhgsBtYF2E6VhZCME2/izNrHlACPngrT9HQr6Ki0nCo0rPfAqkhSgiTRH1eBoUQBm5uRTpLUmSK0yKbPxnh6FSDmrhPrZxpRdjlAMUuamzJCDt1OOELd16E+b9uiO1qrQllPQSxmpFkGk8RYzVsvNNNUJugODHk9WNBI5V6J4i6Xn29m2AhUWOyWc8xNQeN248n9A6as3A02rKYmuoyi2gOoHQZ/EFWP/9shzfFCqufq+Iwh/H7tPodNi53731l8CwB6ffG+XOVM9nZqRnSgf5SRzQNbUS/WZq86yV2ux5nj9YDkYLYOru,iv:0GKq6sarycojZNm3YT/++HDkL7zmW/MmY3xdtQT8IKI=,tag:r5GWSnN7g8TYhY4oBZCshQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:zr5oCCTgcwrEeNn7tg8pYL6A3Wt/0TV92CdG02j8j8qxK2ciIsuJlQZNZ3/RPJ3eZqPTl13qm4nVnpbx3oK3mZ11t2aMwCkXCUovR3Th2VRlkyOj6qxOT3F6utopy/0eCGArRyiXiWpNM83KnETd0h5m9iSvTNS4TxXWCazuX+YPLItUhI6KO7KZjQTtuXxaLTwQj/61rwUiQS4cWxJTFvWa4WncYzQxrta5VEVaxfKq5tkyZB5uY+AbehWZPK4SqS36zEyymtrrx18ISA==,iv:Tzxn6oHaBXaQ9N5JwS/wwLUWVaIRDmlbeFBxTda1ifI=,tag:AOnR/1BNPCX2jvjG0ka6ZA==,type:str]
    known_hosts: ENC[AES256_GCM,data:AKDTiy1YUfzUXT8Gfk80V4FsNKQApFhReP+kdopxASUk8b12MDRCYyX/+1pUEm6Vdm66Zn1tSWwg63UbIjRVx09y04ctGtnd19nJohfXyMuSiC3a/agpBKHS/IFUD3xpoy3JbPwTEptEj/A1HANCERDNzYNH9uM9fig9Hfc2N8uoqDtLeuElIH0UFu1mAL8P7sA8jwq6czfAd8Uyk9hK+RiK7xJo1vlJgeHN,iv:W35jqfnJvEjNIw3z9SGvgGCtgQn1pIjQUAaoBzUG7WM=,tag:hXK9nESK/1sO6NCoaTK6eA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQXlZcHhSQkJFcFJwZmNH
            aTQvd0xLK3p1MlZ2ZzJTZlBXV2JzVUpCZmw4CjdocFRCQWJHZmRTV21rQVR2cXpk
            VEIzVEhhNHZCbzBYd050ekZEcitqeXcKLS0tIHd2N2IxZlQxSUdxVEtOODFGcm1P
            WFBGeTZXM1dkQkhxanBVeFUzTnJYL1kKHh7losK1s8Ui+Qej8jpfKS+H2nVX4lwc
            AgaDSeO5485X3xPPX7RTbhzHa+VNy0zbklncoPH9qR+o5pGL66bxKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T23:34:32Z"
    mac: ENC[AES256_GCM,data:kloal8y2G0YH1VcLVsaiVEMVXtzAEmKvvIA5k228WxeRXv/LEyhbrfofWfO0DB+EXVe/OBP1idO1ZkLVp8qSjigV78Y3u1crN7Qn7lGscfuSKmNUUVvaJy8d78rBc5yEPh+gVDBCi4iKSdRXR8a64zQeahqmvX8faK7B75FRRXk=,iv:/I8ZpY4f0MmqTi/JQgqMfT0idPikDqokCmcgIeIqDR0=,tag:TUp1uw0bWN29VDDVnaqXAw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
