apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:10dLpcgzhSsRNUYgapmCs7COGCBfsojVwZkeH66QP8nO+Ize2OCPL4SKGMFPTWZK74fwQ0mQ8Mo9TEruxM+b/cvMMRhu9v/ZHnIW3P4n3R6czQavPSwNsxWbNcBD/oeDZF+g7jJg1SUGykf2JqRVTXARQSdPTd7LxPFEEDRpFy49/O1+wYMHNZBCaKxJJSHuBGIy8oIGapqv520pFLez8WCNzjtFvTF/sbtcC6qc42Uv1qVT63Sxgz+4VuRDL8HiHWwl8xqypwlskSi2dE6aH5xBwF7DFtnVW8F9V+YD6mxIGLc8hyPZLIE19U2sBNEikwCkKAVD8mmq/I5w/DDFWASPnWhxaPFFEsqJ+hZWy4y3qHaZd7nbMaDocUOU1G9y,iv:A8kn3vasyyZG2EepD3fEW6ZwulEcDXuAwLzxRam4XhM=,tag:67ocpNe1TO4wX7XdSfCh/g==,type:str]
    identity.pub: ENC[AES256_GCM,data:xOemnPeIZ6P0QQxIsTh9ZRvyb/HigCmRpkWAuHpIJvFfufLH8F8yaY8na6JNcYtsj7QVxavEQt7hvGBIOT7FCva+d2BxYuT+V5D0kpXqITUhGuxB+WnF/oXNQLVF/VN9lb9QW5DVHvo7X6Upw5M62i9Mh2G2BSMN7481PJME8+EkeRAfvQB/Rtz4T1ZC2FyG8CHNOfMDJFzefI1K5eCXO7IxYgw0k2fDj2OSe0ulcQOHHHy/v+KIWHJ20xb+ui0Mn6fOghnFiYtWha/KqA==,iv:5pcuT42deqAsPPH9rphGbJwEB/HGwDy4yG+jkj8Ypy0=,tag:8RHEwq5Np/3LQhJbrlHI5A==,type:str]
    known_hosts: ENC[AES256_GCM,data:Ld2Vy9Zp691quFi+2l2TOEDodNPL6X8yxm4uFHSrIFmalNeptRYk90AEfRRvZ+skwG0I469eXRgUqrhD7gTuYi62Kl1CK5IAy3TNzft0M2aA2I2bW53nVgFhSWPwTucIno6LbII+wUwdIk6VmeGCtERPilmEM9rS0lZcy1lReHnR79rET14aUnjHdS7wc0MiClY1Jcce5M888ve42yT1gz/Od7pegJINULV2,iv:+jmp05XC9h0YtQeugNEWYY0hOznikHZnM8WtxwKtF4w=,tag:NepgEG8teA8bAoC8fF/E9w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNXMwQnBaL1JuU0hSanRS
            amJSQlZ4ZVNiSXZQZGFaVzV5VlloRGMwdHpvCmp6SWpYV21xR2VuM2pXWmxib0Qz
            S1Ztdit1UzVrdUsxdnFHMm5kWGw3VTQKLS0tIFZHVFg5d1Y4M0EzdUI2VnlOSjZC
            bHFGRXF5WG1teUZyMzNLbmxXQkk1STQKrUI0KNyPXeaTQHsOZ6CQQFeHNfi+rx3o
            OAbo7ZCPTdId6vAta5vxAx+NuuK4HSCg7Udg0ckYgBQ5NiFP2TWH7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T09:56:51Z"
    mac: ENC[AES256_GCM,data:E0D67bb0t26B0tTI080g7RSk7WfBt9uh60I+rJLZxaXuhLYTKyH8KTMLnnUIN6yeh7cdG78xVOk1t9wF6LccH5jLIL6gQxyaPR/Rnm4KZTmvIMM0yR1/ZdQmid4J7BnMrQdKpNl3wBPi9xdx3aVVRogker76G0XzghnaAFbwv6c=,iv:VBYrLYS9OaWSf6D3+r6+Qin7oQiYVnfiepKMqepPQQs=,tag:3IXx5jslGPzsp/jw91c5rQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
