apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vUq+OzwYS/Fixrdt4hxc1SpR5Nb0s087e/jBo9dLJFlaZzRka9NFmGiGzKH470wlCSCCUmFTzcwKXwhFghzN4NqQ98kcDlnq9pZwMxo5MjQxbYcckAyVz7cUuoyL766JOEJcszNPSD0h/yGK8PrEFN/9bhAa4SxY13StIgD4ok4eTjbABscKWHQtBkhgUcTWNZYKpdK8okh1Sqh+wbDUaJJoEHPDxgnkz/A7U7ofg77/fiW8GZbC7Aj6fQzVgZuMf3xs+FTH6vTPcxyFtyd6XMe4dzp+IJ8LcrTjCDOo7U5VHQ9C7KqjW6ErORoO/J+tLQHipqct1b2oShJUusGkiiV2al8/deVCNUfu55ANBbxkN+ovt2S2wvrmI8rbG0VU,iv:Wi/WzDPszKWXf8kVcM3G2+k1NrMQHjViX3zdy34GwrI=,tag:e6t6BKvbbopPh0wje1BrmQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Dwm938BY9LgJfyljVczCteHLna0oeotX3dbCAUJOuQ8Gp15bcJFVRHB7L6YIDc8Fua4lBpaw8rRGUUuiigTVX3Q2Y6Xl6xGDnUih/OjYvqZrKyu3o6E+r1RfmpSWppn1jx+u5sHRZq2iK4u3W7Q5I5qQdn6dHw0LZ1KxZOl1eeHamdX0OTKCvUD91TmygDJllvi0/Pp20pzhDmRuNwJx0jZExmLicH/8+9BXTv8UChIx/dVPaSdjDXZnXyV6DvdOrVQGY8790DKb+UdgEg==,iv:l06pXXTJ1+E1KuSGtobeXdx6Mn5bDWWUBTcynTgus88=,tag:GzcpjSOuXc2sf7syI6Eudg==,type:str]
    known_hosts: ENC[AES256_GCM,data:E9vt3nzvVrmt+kJmwHnPr21bykfl7OUCDbd+dJLjUcAoEkFxdKriocll32uCVhD6EONtnl/feBwit6UqnvMZ5zpaVNU0v5OUZqSTuWnbNG993ym2yjHUYh0o6Slvadr149jRotU9D/bguhyx5ML4k2fQeKejwulmLuTqk/AoNU9XaS05zhnpIPFO7gU1l0EJo/oje/TaRnHsYBS10YiXi4dVrHiMULsOcySU,iv:ZC0qLPayr/UEXBPjRWZjhIV0C5hdChWCCgZbD3bW43s=,tag:geQJUNiieMFVa/2deHkpTg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aGdrZFB2cVFEbU1nd0JE
            V0RTS3JDYVZUcFpEelJNaDVxTUFOTWxDKzFNCmtKaHoxOFdETFkrbUcwRlhNTGJY
            TDBkUTlaNFpPSTFGMGNKRjlOZk9VRUkKLS0tIDNieC9wcmoxN2F3VysrdHIyaWxj
            ZGJKRWtPMmkyWDlVajMzNURlaXVhV0UKHLB9m7U/QfL9QbHxGgR9P3hUL5JbkHVu
            Cnl0qPgxKurvJ6WUvN9zChO2Pi2a2WMAJ201NNSdRF7jZg+Oi/Sj3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T20:54:37Z"
    mac: ENC[AES256_GCM,data:ygryQqIxM8nGBZNKAqrNJ9sg0rxhVaRPBDNBkBKXiHucdztSfMqwKQ3k+XXXUiRjItGESvtiwNXcbFDwToGK6ifRihgmIVqNxcmODI61sU1eoP6FbGDs+hBgsaUz646BEbqhpK3XjdnmZMdLtAbXrG9/yh9diDndQGend+h+Ihk=,iv:rgOLQc02NBy7GxljTDIfkenUVIEcRfigldYRnMJ7ZhE=,tag:YHWu20+65luxXJ4LM4kffQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
