apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:cTJWnUmFcSY+3eMNqyEVCmR+C0mjrnIg0b6MVOT70C0giJ6vtjEogjRfldC3D+9wu37osTaTkqGQcjX3Dlpf73JUiMDzu1GB3VQIyMTezwso5NfQ/gjP6EvoVI4t+XLJSRSpQJU6cTCddReosuyyIxZYrGZCA+JLbRM6v8/OSBOqQLxwUxe3O9pHp2tEmRHZ6CIVYoP51yhcoBfDbgahFy/9lhkU9TpiHKMyMcX50sR+B/RUTNX/4C35H1R/eagzYDPfOJqyLo41Tmgj/aa4CRWpodzKikSLMzko6NUUxps6kKv2RPuqU68o697UnFnAvaP6qz7U7FEjLZvMBoUZAZfL0jfpxtdHRhNaC5rChJR1DJ30sxmCQfJxkTMTtdqB,iv:+0eHlFfjG8YqCFHJ97fEd1+kn8qDjyghsHHBTBn8EmE=,tag:4a95jiEev+qeCRFgyFIlXQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:tyoGlZIIjNNxonkZwmt1izR9PUSBrYjze21VKNGpRJ/2zcNexWL/1e/bGmYH685MGWpXEL89MvGW9pEM1Z993mPEp4EKYos51fW1+GeP1uARMnSQtcD626GUwIfyD4emA5bJGs4gLfK4PWgoQL/pvYO3NsR2NfFZNBZ/CQB1DMbGw+xyr7pwSOljHWdtwFVQ01wAG8ZKV4kKNhoV8jYgXQSR3nwzYOnvvvpiQgkAjzlnO6lG9rsTJKpNdoGWNLGOK4tiH+F1cXYsklOr7g==,iv:6PWP71H6qRSk54N6432j2NgyY9peCUqy6G8gtQC7xXU=,tag:Uvn5eh0txshvEVxzzX0g8Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:JyIYj3Tl39hEDLFhVvK+vourCuYZ8jr1Ojuer+dJo0dsYKaJJ/bpeG4z4mecKaVylcYV1XBfAmcGEVySysprQofns578wKxP7C5rmUTeMl8le6z7jBI/babrmInc+AcoIZsqPghdat0DRTTby/zUlqsZMMtXp3TKmJTbYGqHwcwjPWQzLwxqbh7P1ZDv48PvanrMgKAMfZxphwWMK/ZVTEXTIbnfdA3Fg2Xo,iv:WawKFZCClXtbSZWJPoLZMVmSC2MJW/X70LtEPRztKns=,tag:XEuKsDZyvltJlJXOQCaBKQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKY3UxWTZUc3Zia2lKSnND
            eXc0bG1GUkNFL3pRU0hGTjJkck5hRWl0SVFJCjQ1ZG1GZmVWWm5WWDJzQVZBNDlC
            bVpHcDcvbzlZU0hqZU00Z1NuSWdMWE0KLS0tIFpaNkNLdjBWdXRVZ1o4V2lPRndN
            STNFZjZXUFViMmdlNnVScmFmcDJRU2MKCSEXLErcPrZMCHuki/RzlT5uaAV4U1MQ
            AvhEhwSxUkIDVh3RqptWNm39EfzklRY5vtbH/Fn/V6rEvt2qLUWvOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T23:29:15Z"
    mac: ENC[AES256_GCM,data:JKEfOgi4yLlDSBxHC2ZuG+lEwGaoG3qFmciRaAaWYN8/bXKz+1KVl3h0/tUjNCY6maspZahc+u1KgNJlfzFdf3m2sjb12snyfRYSyQVr/ENVU380ToRy1aqjfWldM3q2423mS+O7IX9pPsLI0V04qY3uoavD34ZDQwUVH1DLc6Q=,iv:XkhKYojUld81+m6Y7dSclnTR64/KgUKM9VymzbI6l/Q=,tag:h28LzQ/tU4uSKZKRNYrY0g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
