apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:OueupJH4W6AJTV5YL/e2mfvANDdhR3o8d+boxMdjNtnxPX1NQlNEsgWNvUDhAwdwskmZlHQAGgn4Q/bi62jAlpKCv5bcWBEJD6AePgtw5ElcOudYeVLHComJdyd+3GAqtoszR/QAcxZFFzija0sin2jegxRGJ9iDPDW9WbWSSC0PSzByoMyefZHyWGXSwqyupHcEwJkoBlk8gMPbTT1win+/h1Au4dzQ5YH05JNmLdeD6Q7F9CMLXppEYCnKATuckPMA8p3xX4P8C3ACSruCSn7e0RSOQ4EK8WVi9QQDbHeL1hxFNSnM7QxUxJqXpkSkcILQsxKseUVzB7BuJEeT94B3rtyXj7ksTJNNg2NLo5rWjnX9OPb30H5eBiGRj1hZ,iv:XXTvxWw9KiiZhnsrQtsQeDOzl2+oeK+CW/f8oCWx36s=,tag:uMPsI7sgpY4PRSejCSG9/g==,type:str]
    identity.pub: ENC[AES256_GCM,data:I6NVqysjcTynoJJ5YpLnGMh0LPrHeiyQoP+vvIuQxts9DTA1ocot8mZD4sZXYjMLD7MyWvjA5G3X3jlemiguUX+Sf7DV6xoJ6/PUj6HscOcQRyJohGcwNCoQmAPdLpithCIb8tvM/w5sen3gnqJ0PzFoeknRVXmE6y8fDpNu49Amzb25LokjutuBtZa6OcW6yQni92Dlg6ufjVfVOV5yBosnKmcor2Qu3Wx7DAsYG5bxD3BQ1ss/Ju24IbO4xBEPuszR4ZNmgzZKiyq9jA==,iv:EpntmhqHuxdusJphp847s3Iuedcda45ynPwAWRLIdN4=,tag:OXVuMgi//nXPNHF838ktHA==,type:str]
    known_hosts: ENC[AES256_GCM,data:foRhvdEsFa0GczQxtml/Ntw+SeSqcbHt/TaDxMQ87aD97gPjvhwFEZZjpw7LfVP6TWppUNvimXHapqp9kjHjEepRgiEOLbWm1XsDS27Cm9HYQWcM38h1RLynfyK/1Cnq9xhssHVtBb069n7OfWXxAmeddo309vbeNWmLK9MtZIozAFxjouJYIoHuXFtIcZfxyASALKfWKHqzuOJCIm2CEzRlA1NiUYZII0jA,iv:+tSs6pmRY3pq3+2GDnlP+zZO0ywgEyHlT9gmNSF5yEQ=,tag:IDTz79UeNm/hcfvHg2gOsg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTjVkZUJXSi96QzByQ1RY
            aUtyeTMzaDR5aitNelRCN0M1a2c5TkhxdWxrCnZvVGE2OWUwbGhXRWVBNFp3NFp1
            cVI2Q2g4bm5wZGZXLzkxUWpvbFQxMmcKLS0tIDJZZXZYem5Pd1JleTBEYXVLTEt2
            QUVMZzREUEx0ajhMZUhmdGxmL2lTN2sKeRIb3uo1ZINo4ac2yaVL+hugejb81a8/
            VwpNKAm4kWxE4IrADGWO+f8qlycwP7Pc/tdvd7Dhtoqg+SicMw6JpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T09:54:20Z"
    mac: ENC[AES256_GCM,data:OM2FF/DO/vJmARPqB50wxoUYheuCRaSIyFQoSykfbRhZWWxY2mwTowxI3LW7E4Vs+6AiKyjCrsJ7LkkvVHTkqgwYMXsED/TPO0BOB0s3mLrBiwvCQ+AVzn0mPOMtXqoTYXeduF+SDfPuHap+TMLdn/6nzZyIYkjFDh7ArSQlVqw=,iv:ol4rg3262lHTq2mP/sn3bj4y5R1vtFOX+eKENNmVD2s=,tag:+vNYOUKJWp1qR7uOSyI+gg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
