apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:e0pckdVbYXObrd2W+x+h/0v4DeaWfncZdD/BEeDM/nJxfariAvOmUIPCilyz9Q/RoOnqOCY/DZYUEvqk9QCtoP7+wpynrVqdJ+jFXwRACR/qmaOTxfS6GCf5JyW6x6ffZv0Q1gCujZVmDuk+F26RVSuOa1CERsgligWTXczrdSvfCUmfZJ73G3lQo3cn1na9mqvtLnoUW+knHSdy+7mRjuAm8e2HMVAgR/W4YPZ4JkhhGfJhFpShtzMpTM0yNLzGMI3VuyXxP3cLkLLaMN42t1tYqJR48/yapQuua68Iy9oz/isgSDOSnplV+Gn4U0i/mZM+pzspQfmQskHU9Kojr8vCV/0I2HT6R8kJGEvkgZBABi9+G/ew318+ct5SYPP1,iv:2xq9tYdaFBo9715A6nTgiT7HtDns9a5ZmdCWLGomGuE=,tag:ZqfTF1PIdCpslRgHQSb7bw==,type:str]
    identity.pub: ENC[AES256_GCM,data:zaIdfRWtIRpum2cYong3Yq5ynKJT3Kfz1AxYk/YXTGFskN4Z0eelGS06Cq9Qz9hgbY66PkaA6bLjruRkfesKnW2qGT2gasPzApFgua81ZNyggnmwYVHo02tyVQDgccQhLg10YTtxXstBWzakZm+j8OpA3pRaEFmNisdU7IEm6HtM5PtUAf4/JUwQgMdYaGJOpXGeM0tZ8vj9Q7fzLLJ0ZWF3MPCvAn80sP6Y7MDWQZkCTQoad83wS909c+A2LHEhCT44jyGeEPl39jH83Q==,iv:Frv9R5oHp0e9zrUgOI/b+Hq31n6FlUp/0cFI5t4iWuc=,tag:dxGQjH7ljnZqXY/SNHJFHw==,type:str]
    known_hosts: ENC[AES256_GCM,data:ScCDfkKF/cNYfGCaGowcCfuJWDJktsrXtBxyne9OCdQcoeVeOg44FLZGSWOSfjBOs0TsnILidj/KA9Hu+HdN1ZGWSymfGxQR+ufbF5ZpQ3T6oHM2oKz+muO2fd/8DTJBiDnJ5JGDWbftkT6arCZzu5sS3PDXgv5Cj3CxatNLZd4OGbfgOBEkTAxGro/tjRyhUpljHizNtm46y6pvZcg5hXMWsd06dr6bxka1,iv:TPhI8nQdHn0ZwZz4jndbZCeIvQj8BjaCYNosBzfXpcg=,tag:kwV7Pqk3j2zMaY6UeG7wJg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjKzJadjRVckRPZHpMU09h
            aU5HcTMreE96MGNZay9WWTZ3SnYwN1JLMEdRCmNvNUF2VURvSnZCOHBmNThqemc3
            djlWZzZDbE1CcEtvZVJKV3RmUUF2MTgKLS0tIDMrYlJpWU1LRHh5eWlXTnE2Tjcy
            Q29OVmsvdGxrOUJsRWZ3Mm1TRFpVUkUKpcQWON0H6brxGPthrGLRsOJLUbDw3IUg
            m3HL5EkcCNbVZ0qUgFWLASmsWbZuvYgy3vEYisO/ge4drSOxGm4DhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T21:27:40Z"
    mac: ENC[AES256_GCM,data:6csu9Envzop9hQ7MRHzgXQsfr4FUibMaD5pPlXM3yseuobsxBNWsiaXBqcr96Ssfuqv7rJOoL2wJLlIjpZGiU/d2JqiZwHMnUdlR760X+U23CzDNJLZQClZVUmvebFhbl2bh/ZEh28EFu9BzQvUAFife+YtluTdkNmzDkU7GbVw=,iv:YVj356MWor/QdGV0JKvSKhOn7bn5yDbeiCz8HYUrc0A=,tag:IVsPQXWWrze4jVmW+lMosA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
