apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:RZmv21EMZbJrichhgED9u51wp1JyFkn+u1gdtx5e0E6yQ+1Ez9wKb5Wj2cNoUYTnK/7O1gEqzrr9SsPoE5hvZPgSKn6xeWqgrnaRUn/SEXIyPici0iudGUTErDu2VRZKxridKKGbD2XvgsGpKLFM9Q0QP2Eu2J+/TZrcAPgg5QTo8WlFhVUDZ/ThiF6DX2K6jO6dkhzQ7MZ8Q/iIrSo1gL/VodW+V6gT1s+a6xf6p9PnbNMDNr5Vt0rZHmUFAqAbFnKueETSHSL+2Tl7kOfQu00SNhQklc8w8iw2VIRXsBiwqQvhL4zblSI4mIpu1kwj3WJm5zShiGZutwJxdF6yiaBN4sjI7DIQAcg5fQBMSHnnsl4d0o9V/cZYMYJEtz5q,iv:SdzmRndLlIv6CMXwmkfmQqDnZMDqNeGCnSigJR7cDfg=,tag:oXdqL/lbGBrFqHSq4A1PKg==,type:str]
    identity.pub: ENC[AES256_GCM,data:BoEFT/dJVt+pwXuDnK5z0yERvlXbbmPuqjJ459DZ5mz8+jS8E/DYSNG3P+6YcHr9RD/NCTXWD0Ox7y9L2tpijbGCwBHVYKC72cAWEAUO9m8ZZa/ppT2J3DQBnVenZFNSmDONNbLN5oQFpNS0yvLckzbN6Qb0EGCsuqpBJ/c0xJkW6RsqqBEe6CCsb6TW4hEa36hPQb5AsNymzboMM8OoaWDf3xnTs65wzm4dngHXe6EIPXAOuPA4y8FTKMrvA6GipS9TsmnDqXM1hSosVw==,iv:3MY/r7UWpWXVJolcwLuk3zsWpEcLXuKaQEf/Qe8ZMMY=,tag:qL/gkqvDQYpTyffvAktyIQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:Fex5+K7S+hueld4Z0UzPrqyJWwohTALHR3RXvOlfqD30/ZTvHbfAB7VricjARCsdepJDszNULw7cBY813AIi2ufGenP/zQzn56t9zCTWBuufVi9qPtyiFhuJAceQu5OLDpvtokF9AIL74cYSZ+L6aI8cma8o4LM5RoJbD/VZ4CQZ3RV2FuhoSTcVtZpjwBC7VZP2nta2Uz40zkuNrblchMLtL6bGgR6xpiDj,iv:FW0WkSKIL5yKvVFeKuWnt1YaQ59t8R5jX4KPa7pCb6Y=,tag:DyPStudf1xIYpedg+IKt8Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQME03dDF0cGxwQkJlWWZR
            ZDAvT25pYS9nRDMxUjMvbnpVTmY1RllGZUY4CjFGbkt2S0xBNUNaMjhOWTFDdmFp
            bS94RzNrRGpYU2R0UGJGNjZiMVRPUnMKLS0tIERZbElyWFdpQ3lHdythQXptQW9Q
            cktMOTdvTTN2REljcVhaSGkzZEFSS0EKHTnJ4iK2MLFgZHKFrCAgly/6O0Slw5Aa
            Kq+XkMm8hTq3nU01f1eK4Bzp86gzwOrWXrp+BBk+ob1lx6EbovDEGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T23:45:23Z"
    mac: ENC[AES256_GCM,data:+ckR1asXa5Lgm9i+JtGjbpz3ARYB6CBk8cgvx7FZPBKwWZCITwuW55E+7RgQTSUHkAUxeczTAzZEbZGYC7gDscU70MCXkd0At2WbHkSUWiNYTntsm22wekfXMbsctLoHvdy0jHU0bUjjWH5L81IiR27Kx3EJuSNXuxpbC4L2yLo=,iv:PH4RPpB86M+/JTK+EGvQmylOOWabOzwhdOuKC8Okzic=,tag:YmAZ9086O9JRBKqnqPFOrA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
