apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dzJ5MXBWBuX3oww21jn7lups5Z49ClZe9NCdyM8/jEYznB/8pvSW7Piy0AH+TSXEgt+UdUeh4m6RxnLr1jrqqNCCOyEdgjBuywFDilj1ifQ/fFrKA+b1SkZeaaYuvGlzpwLpmjpjm+N1ZmRhZf/wCYWhtUWXIZ/vY13DxBeeuG0jJB4a+MP/1PlBQkgGUYEKc+1hG2tlcpp5LADK74Y1vNU1/oJGqdDRn5x/e/Dl5/HBMV+D+7Se3JRU4yZKfBt7KQ9Y7jZ1r909jb+K9IqKTgFkD+qe0S+VbOt3hC694O1tmkK7nocyqZgGuk1awDZMCJWlH7mYJ3m8xKL+7i2ERq+IWm5xxFqYArDtojc5F4m0VrqCo54CTwvM0neNoBR+,iv:L4dm0GEf1sCahSM+zgJe8Exyel4Leib38MGj6PWOoUA=,tag:2FfIi4ZTZJUU87CDk37Hlw==,type:str]
    identity.pub: ENC[AES256_GCM,data:UmkQPj3+lw8mmTky9WVy7chrXUUp8rW4GLQC00yK0qr+kndocKtvjjLeTDIaHB6p6DJvIBMfrYyPZyoy8++enm9ePtyVP0orC5WLHl8ElW3jlzAuveaErtfcrhOHNDO+UGyQMGB+ZDwqwpG9e994sY88xYmCKrbNct95qrdinVjSroNmZM9gXmemEuykY1IQXksuqT5ra7N76zINzEI6Kl+0cnHODYAyU+jH8/BIHCzlK5StWS4znGasMeS6/SA9uea0QyxBdZyzBgkeRQ==,iv:gLJ0gXTatoSSrIluQHx28R1IudHPjxf1XlYgCezQHV0=,tag:AVtGdIRuwcugVWw4FZqmBQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:YP5+M10S0khU4joY0ZunPEJwpjWf4qLEq4Y08Y0hHghHwxMMPwfXpv/8yxuXwmjH7j+NhbBflDZuJbUR+BVAf5/kLJbvS5RRQc/yeIFcXtmY9jhu045cGBxUZn89MQx0mc0/pVNQmx1xeQdQf9ArqNs+7tFgmwXFJC1lmOvmNfhNo+6ntdo9oCqqdN/LB2wBuZJuxSDLGCrArNG6CqjLIIw8t7ZfQdt1AdJc,iv:85+Fy/jUbwQ32feBk6+APQHoykIryuYbQoDD8bQKaB0=,tag:KzoVVBsj/R+6qz/XKQjkow==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwOXJYaGlGMnd4U2hiaTJD
            c3ZLYUZYeHk2MmMyVFM1REt0UDZXT1JHbHg4CkhIUk1UelEzNXBKNGttMS8zVklt
            cURiazJQSFNpU1ltYVova2lvNHhvRGsKLS0tIGRKdmgzVXdwRGdBNzFXUTNIcTJV
            cU1aL2pQakRkV1diMDJ4aXQxT2trb0EKoVBDybISrmvYqQL1TwxrWvTUSIArVRfi
            wFIzR6hEuzhvZ6H5Mp+XxF2XhRn7gpxg5NwC6y7WrPKoBLf+5oWf4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T15:51:32Z"
    mac: ENC[AES256_GCM,data:7Ts1ZDcKfg+GCMJrz8kcH8RJTmFgzACJSbzZpAio7PueKbSkSwi7HBafiGNb7VitfvNAn24bsCnPGTZCzbqUO+eHYsznNoz5FgS7evZS6aePerDyy8S87THQy09coLqk7Lh1C8S70t4h/doSIytmwqYjC0I8UxHzJ0BJUCRF8oU=,iv:05uj+u6vldTAme1hjrAmUdYV6cgKO1usSDforFJjY8A=,tag:0nDd25WgOTpESE+msd+6rg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
