apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:fy+fBgGDUQYD10qV66k5vbdL6NztShd0ByI8CXo+8DFFiPIm1BBArktoecJPXqQnIUkG1O22AcixGx0qkUMOuXYcEMRIFlxYJu653XeX/gpFn0LaPM4NrI9Q5A1fsWZ9hKZ5T03jXxcWQYUe927pAZx6uijxfhiMM92p7WGgksG8/8PcvJenpM6G6FFFqpXv7F8VKqwBinXA+zTS04XgLt7346lOlfKTGp6+prW3Jx0mhf/5zaKypMXmX6h+UrPk/r36TYlOO9zHBGxWGw6DYoipKK9z/nG5ERFLet4TD6/SUbXD7JlJrSoA5cVc+pdp0A74KNjW1sOzuECppI1LexJ/+cwGFzHuB72o9lNx2+SPlVd91H7d6Vm5pav5bX+n,iv:ZqRx/ohq1zGieRfaynzQJA6Hk1Qg/Ql83M1Hj6CqElk=,tag:bCukYSAZEfODT12LKwbXPA==,type:str]
    identity.pub: ENC[AES256_GCM,data:zD0J7SGK/XA0F4Otcu7LePbiZjHM4wAGVlEG+LXQYvP+tuIOoMQ0jw2tOxQib13p5mqnD+611cJEkNtIBOGUXgZgUcAIQh8V/kJXhgOl3wx2c9x6xYHxfa+a3z7pQR/oW4SwsojwhvgBShoKgBmj08Zpl4CtuCBvSfEu8vHR5r2iDfmAitzAf9dZmyGB4berY5w7pSID//O+LuEttx+zy9UsFAx6BKYxny3+8Iksy52YF0m9Jbbd65x1c4M1WnNn0TiGOzHNR4JLci5QSA==,iv:D6xHHuVT48r0XLquEvaskWDnEJG95vj0z3I3zXZNpdc=,tag:wIh5Y90o0ms5pP2RXjG4qQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:9cX00D7UhiGfiCJgzyKnCRVaviJ0ZoLDH44/MIyayHr6AhIK/xP0dzHVt3/GHBIqmFA19BFESq41Z5qpF/mOvK/BG3h+GHkKq6quMrXe9Po9Dd7FbTDBX3BxjAbwnGbbdgyfQgRgJrA2HfhAlJPMrrUW7cn1vEZXMFn5UfLhncwhFtwGYPq25piz5/MbMIULvXt4XG4AjNGGGlQB6IIw1mBCARU7YKa4b/1D,iv:8xkWX6Pbr/etwXjZ8Kc2uu4V5ih7t0/SHHp+OHnrIs4=,tag:Kn6W+MUG7I768fvpAL+Qww==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVUUyWldtZHg4S2lsQ24y
            T0p6RWlEWlhGd24wMm1BVXA0Wm51a3RRTTNFCncxZ3FXQ0JSSFBjUGVsMXhvZmdx
            L2tLTUltcmtHcG51ZmhzN1pMckc5WVUKLS0tIDJ1c3cvTk1rYjV2NFdQWjlFbFox
            KzdQcllLUjU2WlQvTytkQ2ZEY21Ib0EKh8VyKH+QjX+TJ/bPJk65eFYaVs7QhMiV
            O9zcsuJwX6FaThdsuCdM0Pc7ykjrahZlSImHZMIG/NcmtllN5nuI0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T16:20:29Z"
    mac: ENC[AES256_GCM,data:B6T03tft6qglhwkIVgezzEwAIj16KvK30Nnj744m/758BhPfQeN58qmf/5dOpXUjeEecbPh/+PGIrbYh2HmwnzSt26EAgzgf2bgzbCqxzs953wISkGwu7t6SOWTXs+9iM9O9Xjvbx7FRTNCFUYOEbFTwW/lFcxAN9WBN8jjgsns=,iv:nK37DTMU9qmCLauyIbA/Ez5r5fiUfseyu2MD2ghr7bU=,tag:8izw8n6WvaiyDGTKJVHDgw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
