apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:x3xkxrv7piiFpYfK1PeSabR1bCXusQ7olZyF8IBFhAxt723A2F1SqKrMwQY134JPI9h01ko1HWWjeGJftVlKVeGn98r5cZuBytf2Gsazj95N9Co5lW8ugBLIFS/8gvRND9EE6aEaSFSau10wkBmSHyZhSugJ35bSeQXmBpHZwLCyRFEQVl+NU+yAUYclspDHmnNDcOT/tVgXQaj0S7PCpjep3E63NGVo4ukSEGdR6RcgDNufvS8vDHgBU3HBFax5RKiHS4ekFg8NBIFXwnbKFMFk8MTWGqA6sOQWlsFEsTUZr7mJfdyV8lfyoDfCjke/NcqABmSGWqj4w6lFEvXeDkNTD/vndnzpqTZJf5WIEgwJ8fWIpZJG1G7JhKVQhiU6,iv:s2jSTRz1S4rmTM0elgokB8j0cNdZW6Iv7VR/RDbnNdQ=,tag:84d0RI9zI/W0/8poweaumg==,type:str]
    identity.pub: ENC[AES256_GCM,data:uHByF7bGeerQcBUQkoYpOqvpxHxRzzfbSVOwNcFvSaBBYj9ETJNnonw+ogAGh7K40wPqMxywfsdqpDA0LchYGqggckqnQQDqftKazgbtRv9w7j0fNtsKiNZU9gDi44kH48U6dbLifun1iYbw8e5MJKVZ6guv0Xfyxli0TCPz4BrMMyKIeOjbcrRvQTncVsv/dn/JlLNqkt6Do3fqUApixK78dxDAKBUYfvkLpl3cPn1jmh8BcPq0tgwjCik1SiVBnJBl0XaOtEijH7CUxA==,iv:8eaJFmUe/NVyyxOz2kDRhaPLOe0Skuy3OD41OxAD0Ag=,tag:WutSHu8lK6yPuQI8Hhn8ig==,type:str]
    known_hosts: ENC[AES256_GCM,data:UIVXkE6ob8kAJYQcrHLce/KI4wH8eITAuXCQeybUETlmwnyJQlyiAWddu2V2u0VNtuLmSeOsEOhuSb0a8aitBbY/UxggKUZ9FLn954K7keaB5o5iwJ1Uo52wuH91FlxBRqhzN63xXBukzgQXGd/HVjggneRDQzOEl1lUy+Gec+t23AdRhkJP+BV4nBdbPLvVOlQrlvaQt+1IRjKm8jSgS5KTN/OaUs0qGk3U,iv:aOyX1MurTjW+bV+3XOHxVw8YrI8A7y2OH29gbjo5+DU=,tag:gULdO0BSpBS5YmPSv87Udw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VVVTbnR0c0NQUlRPVkFB
            NkFuVm13RFd5ZE1HRENkYW0rY1RyeWQyaVZFCmFSQUpDVHl5Z2pHTThWQk9TOHdi
            Zm9LV3U3dWNhaVF3TjhMY0xzeTFObUUKLS0tIGs1VVB5bUFyUkhEQm5qNG55VG9y
            NjI5TmwxeWpyMXZiUk16dHpDc2twMjAKnMYk6W7QquxBCFFeI3v9r4yVUMYk/CTy
            JJTf/jjcGQtX6QWHT1ftevWljeCbrBEnqKQntb87j/D+08N3B9+Btg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T13:10:47Z"
    mac: ENC[AES256_GCM,data:3VDWXkNAvOpPg0MMRQfytE2URk+6oIzU3bTZyfUhbNQ3CojGA+GUwWwOXB84qfwCbo9tZAF9VyM8i+KL/PuUmC+eQBT5g9rSLAjs8IanLuKzvkq326mdf0Db2T4T/Dg+veitbnqpkZcr8chOQOqEOQLajMiudE/wO6dvdM5umBY=,iv:hh0oS7huosjN0ex2hAuY3hTRz3hoRRmvidF5J7YgJpQ=,tag:6wQ05tC1FlMJeJiTXKAPCw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
