apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:EfvE/A4CILgUO740wS3bUGuP02iNNZP4C3QeXEgOjPubINs+UxYewcdiGXqw0FRFWWAll/xjqUkxyqjPiNgVQDwTByKewLwXAlKSsCH7OOC7HKt4HYXg33YnxzU/M+hBZ3c5tznkalaIbHJX4EnSVJ4d7p7yoivKfn/TKIohUwgv/jBb7kJVr8yocu4EV6SZG7NQsINTDgacHzgZTOamUijMNG5eWzSRTR3Njc+1nvimoO6Edz0datIzPBxSgW76NUTvquW1tUBbVCZXlLTH8L7TMZhWDqRjatN5B/kEg6WpkBmowBiig0XO5IR9wickP9+ZqFz4+hGWYEniDegTmLcASVH5xCKrlJWFzFJh3WqF2QfRbyZB8H8UT3S/jLkU,iv:tcvukcSOdt9qEX46jwJbu8YLl6vK1pIhWu2N1XdkyRQ=,tag:wAhVpeN+zyY5RJ3Mqw6scQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:CI62LKAP0dxoSz63CH4+itfSGJbflV1/AZXxbCGsjyor7wQ4G2ToEjhfa8i5w3DR7Gvn6dAH63Fj2WKUfPzn0xTEos5Yf+/cLoJ5a1hHxAARwPm72ZXHQ5zJr8ouRmmnI5f+6mbdKPP4oWlDBGCD5GYKLa58EiS9aIUGHa958BoA7mV+Q/C1eVmjaM8wMSV3KWtZ4PMMTsz7iRmMQIuazsVcOwTBhDyjBZnZ1+QIwsu0MqIWkGVGoCjfxCgH57MHiDdOM12hggiT51wu2w==,iv:/O0elHmvi4BHfsCL1GnXYtmrE08oFxsIHI1uiPkl1xw=,tag:8AZSDZQgLVwgqCg9xTRjQg==,type:str]
    known_hosts: ENC[AES256_GCM,data:6SG83XvjgcYsokjL9q/g3YwzSDRkHPMq5S+31QLlf8tean80VLOcojcdM4scl00Y+9wWrWSswKaO7zpwE6/Snn8+8jcg8bfr1UxWX4sK3ZvXbp5CPfm/UqXAR5zR3iCK3RQBmjG6e5Q/xg5JoJfVPEYqt0JbuZw5n38OekghgsvYWgCs/VfqARNsN8yrogt9TSJv9th4ZDmSXTtt045Hu04Msp0m85Qem02i,iv:ebqJ7OmhHnwyP3xnBuGpaLJ66P9W2UigeUXgDMzAOC0=,tag:5BUDm7qKe7YOBtdQJNg4rg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TFdTRjJpWWtuNnlPNXZa
            Y3lJK1dmM3VabFdsSlVPYTVEUWJRNHZON2wwCnliOFJXN2VvQWkweXVzdnhiR0VR
            bDV5Rk5mMDBLMDNpYktNUVAvdUYxVUkKLS0tIG5tTFNqREQ5a1FSVk1MbkpwSVNo
            NHpyaGh0UmdEcUFKTHV1MTNWL2E2WlkKyck+Dpff70CqQ0lzeG/IT5LvAhGWllV7
            BbyxCU7Y6xGHKGAOX9n87yUheFoM2hcJF/qCu/tUx+dPui+enOrd9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T14:21:48Z"
    mac: ENC[AES256_GCM,data:xUpgpu+5ngcRutgxSwtYBjeqY2YZmYsWQ/rqr1uGLhSvUoayVyDAfZGVOzndrxk+5VlSDjX1xziGkQOM86u68ziyZyi8ha4mJtEIKYAmtPMisLj3O45BvbxaNEsSHipgRsgiYbD2o5RCNabp+ls11ePOP72vjeIeNUvE5aTASbg=,iv:j4JVosIl54aTwPCbOcqzVJ8ltjV1PKbrJGUHx4s8vxY=,tag:eu9dm5Ykws1T7z5Qrs3sDA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
