apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:xQCrqR9vy3xfoihAKxM9QLo/p9lRM3eXozhurQ+5VkH6WSUt47tEnHPG1/TrrMsxN87bGZtwwnZX19J9w/b80y2UmLKB1nrvNVioOvqlqHc2RqihGBSi+KEdvZONmEZXAoXgvuzw/NzpEqW+IpS4eD34hxAJnHunnWoPZLdyE1hvL9DcPCYWdvEsYSIw87CJCHAvIXPzBSXDQiCypM0WnJujk2S/ezz8QZfdm2Itww17zadeBrISdF5BNPVQUYkzlWBJLUl2btjp6WJ+5JZBZ4DlT8nNx6rMqPJQLZWqbgs1WrSqt4OvidskCpQAT+svMJsZu6bixBN8EhfsEDFXzqijRTa8Ap6DMw/bcjaLBWRAwUNggTh5Gafq0zwy2xx+,iv:L326tr0QhFKLs4vrXspn1CMuO8NXiEfs2KBC7BGQ9HE=,tag:7e1Oh66hfASldAcs9HX+VA==,type:str]
    identity.pub: ENC[AES256_GCM,data:XZcZdb6kVYGlGDHaF9YBkSQXyCGq95jNXlNPIhVVWFmYocL37WzPmqzKn20kZdzrMsWukBnzTKjB8ZXju2MvzSnA8+K8VsDzVaIDCnbHKfllNpaVnsowe1C6+PqzYtXaEwUQUisYA0LK3wRQnrcwBFHx3UdcAqN61ve0Rawuiq0ikQHZxdjtXsELSCvtPEHHWOhZhioFuN2SCoJlAsmyNjTUYSC+OCY604yLRi5R2FXUl/4ZPWCmDcvgbApVNfhGSQ2ngOY7XBX65RqRig==,iv:Kkza8KmRYQN4f3qlKVrNXYp28WEJR2T52awytrbf3+Y=,tag:c7EZ1JT9PgQa5QB3ih4P+w==,type:str]
    known_hosts: ENC[AES256_GCM,data:dbA/iDCwqsoy04RJHi/2VRIQ5ikkuKCSuX0a9j3Qb1w6naeCO3muDXOEl/0DJ2CJBbsHmY4JbgCJU9CLYGQzBd/YdLVbHS1nWdi1cQitc9LWObEAiehvFHDimTdNoQGOg6zJLrNHD6R33k0NV+cXshGywkceziVV9RKiq+oqQlXi+S3Uk1HqYYELFd4eJ8U3d6oqghYcMVB6ka2lMvqwTvbSfXT+9tYQLQNN,iv:tP8rnbxdprmDcKzvWYYX4gzW2kfwaxP8gyAkwmyxPjU=,tag:bArGQX3686hLGLu93CYTEw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bjYraG9uQ1ZTM0FwMWE4
            VitkTVUzY3lkWlhGVENSb3ZOWE9OYkpIVjNjCjNRbXBVWS9qUmtyV0k1NkdjbjRY
            ckNhMlQyY3Bic2wvZU16bnFVUDBMdkUKLS0tIHQ2c25pWjg2bkJZRW9qWVNIdnlC
            WXpRMTNXVXpvcko2a01MaFA2NkJva3cKX3dm8JgOrJJgVdOra0VZYZKsOBybxtxy
            rn09Da+E5vxmwXfZUin1wtD4/sHGsu9Jw+y5COASrgs8mZI8sLQwCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T13:08:17Z"
    mac: ENC[AES256_GCM,data:ZKPDG4uBTOMWdzfwdZplgqNwxoUlvWzr+O1RTvTAQpLDL26F8REprcr1BaI6OcFRMZXy8Y5SPWzF/Xb3ZKMpvPSex3TfTAW/owYlC4cN3AJQ4ELKlSnALCgWPQ7RX0SbwrOOpDyomfTJNBH0fYooyZH+Pjf1Ul/LuoNgZtYtJXg=,iv:sdWnlR6a/acSodzmsXT6IcwhNa+droW4fNJvT2C09ik=,tag:n0j7/CMWKq+F9rm3vBgW+Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
