apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:xHBcLxZ4urrhAM1CTk3wEYihVqKhFiBB1iSCKq6pvL1h9ltMQof34GQUii5VSPiL8BgVM3dpJsIlkeL6iSRz896xzw6IHITa1uxF0qe8FZTNfY7URwSQJg0QDQZJCwrbfcaOq5Qij2tOPdi4JGV9AGTCtGt3WmxqtbUiUTaU0DghRU1LKnFeoZ+9GKNN4vOledsncmQ9SNM4Efp7MMIVSI2cYS06qWLc9R8HIGSAGJFjMT43L8bivGydBkd7pjd2K8RzzJKkS/5N6/b8K9eDGkyuFYWNu8tNrmBTgt6GcS4Egk8JJZJQjD2wcajJ5U/eZyGGevnnLksppw0oymciCzc4hRvKNi1DAS/HBGYRB3DiTJmeYaAQV83Z0qqLyTl9,iv:H062HulCLMaAdPfKh9AI883JLS+M1/kERN72nROmHQA=,tag:eLgQVK4BMc9AFsWE5o7a6Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:Q678TKP97B3ayGFJzhxYJGFGhow+n+JXx+/CZomGWrh922bof6WJnzilF0Wft4Ujyvyzf6S8q/IQc0LGblI0wfhdagjYZNSvL8K4+ReOhJdc+iWFRYyTr2/r3whPKPLVAv+L82Ol2dm9kjrWs7Ndsjp9aATheysGLHA9nTe88FP47Dj+4r/GUuOF8rXQ8peSRADXc4sir3X0Sv/be71pgazpKeK0EgGpM+ez9i5Fq8FQ7KOGIgEFSxrI/GLYsaUzxUDtkb7Yhfz6cQznZQ==,iv:b4PLe34n13uhpEGhUVz6WPC4LGnJShybbxhrAZ2EeNA=,tag:NwRvjoTTnsJUQRQ1oo7lqQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:OzjsuZqMartFIxWbHxrDWHV/7zv/qSiCHOfBUjlVjlehAWP+NYj6Okm1OBpu9IJJvqYOxy2m0dhRsgz6yTw+Z6Maq1NoPrWHwDVXbpLcnJR/yfl2SrxvQAocwHsoPSj2jFTDB2P86q+oEmx2D9sZqRJzwQbM4v5BUakBzmdncJOK2Df3wAf+FsADCIFYgzcB/auQyI/713uQm0BdGoul079fzQEpQZzAOEOA,iv:MJRIRmZDBU8VJ1mmpdPdOS5L+WSVal1e8EDGOOMQE1U=,tag:62nuYmI5rRk/HAPMjax9iQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNG54ZW1iMGNlbWdZWm1O
            ZG03ZS9KSHI2VEdMVVVyN1ZtdTQxaTNyRkNzCkdEcGNHYWVudlA5L2tkNkJLV01p
            RENNQXJ0NnZyT3c5RSsxSHIvRUlNY0EKLS0tIDB3TC9JOC9GeldSWHlnWWkvbUc3
            czArY0xBU3ZkL0JaZE9DUmFabjI5NkUKqMnzj0FSS7wwo8zUXwaEjHltYccfXUaC
            eREfZtXls4CKJJ6pqOTxD1i5hCkcMn5MpIfs7IE9jydU/fewbF/P+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T15:17:21Z"
    mac: ENC[AES256_GCM,data:N1CUF7H62W73FM2R2xnA/9FFOHKglsVbqUTFYSUyv+sIWDdG2RdxyoOUNnuCpmVSEv1JUxy2K4YX8ztmbnRTuxVwtGAIpyYysqsBV0YCyY/DstEzlkhB0VvkTl2CPzele53bPc23ZJcBJVLBA9bWRRTYoG5QJ1zyfleKCpPf99A=,iv:G1ORNIVDyCBPL3FSuUIQBShZttCNbWCRW9twhmA9xCo=,tag:F4l/eP6nJ+vFibLVnQFBvQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
