apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Mub7j/5X/ybgsV/BwXF0Lp+LIk+8QBmeYmsxpNC6fH0ofGF4MI6m29rg0vVa7uflv+Qntld2jx8LDqpK1+YiDf8hOhrilFkp/WhuWgdiNJL0MDvuxgZ7D+rxUCo17fSxoOlWq36TmqKJXXr8tOuJqNnuf9UOT+YVv+YkACIgqutlz1BT8WbYi06u62BJnMFM5ozkArvJS2EhjQioDcNTewK+EdzTONLqi8hViSB9+vNYG4fVEb+UL3QbiPxLePH7fBMZnDYVey6uZh2p6hmA8xKLke7qk8V6OlsFj8EVLG9CWsps/r5QFR2okYBD6gwWtEwYWxZ5TNPsM9PA+p1+H6P/3oGPC0JkQ/RtrFbRObNwJYiTEGM7En59dr2VG55c,iv:t0+iJua7BjHMI9VQ8K94jE3C3Cp2MgNdica+X9/+FKA=,tag:vi4aCeTzho3vFgAeNucIcw==,type:str]
    identity.pub: ENC[AES256_GCM,data:Hubk0zGBJZ9hK+DOYUEmAW8hJv+mHZboCcvSBczjMRgsRFGJ6yUVGuFZIjiITO/zKlJEe/dnWKY8fl3Izzzd8tZmGMLFG1JVwYtuZKTPejPgQUe47AzPmQJigtMw8CJmKc9lhIyoWSfcOdlYo0P2PCiH8A0tCEYnYX17QnePoVpHH4KvMEVFyt2fLTfP8WRDHKRQ7EZPHUZR6Ch4lZ+7pcg3QrvbEjs22pqIVNGOpkuBz9YPgECKNZW2ElIUzw1QQsQmw5BE9139bYL2yg==,iv:DfmipazD1RGxD11tHv3LIs30guaQHUj8IUBzH+Gbx+U=,tag:zmxAv/A8iai3gXYNEbMTHg==,type:str]
    known_hosts: ENC[AES256_GCM,data:9aP6wSPVRoFXQlrHF+etR41VbotkrMCRlAOrFNoyzAZVBJ5VXSwJ3Wh5DlkgrMFKbt6/V34LQU7K0W19kT+1k0ulvky06UAoj3L+4qEGHQx4mXiksH1KnXv7JiF/L8Lvn5tkF7FVzzV80QVjR3+But42xdbSy31muYitA3df+gIOM7DrFgArm/BO1dcAJac9+fG82Ryuie+hMdQ+L8pFYf1kBUqlsqnLKiQf,iv:R/mqCk74NRXjYm+3V13vWcAoz1GwcSEd4hBlA4H362I=,tag:84I+yCSgFrk0utnO4e/c8A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQ1FScHIrY1p0RmRjcFJl
            N0I1Q1VjTWFNMmNNdDFybWJ3UDdCRnNRQnlFCitWRGh0ZThEaHlLb2FJM2xJd2tM
            UGkwd0xEUXZyMTh5Zk5OWWx1N1VVR28KLS0tIEtnL2o4djJxcDNHbnJpMno3YmZS
            Ui9HSGpwNTNBcmFxeXFXTno4bFRNWmMKYsVPs2OagNPd9p5KrDHCRrvrx7nrfnAR
            PZuzngRh+tRCPMeS0deWB2/G1ltgxxVl8dW6MgLqwvqCvBRXnZkItw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T15:05:08Z"
    mac: ENC[AES256_GCM,data:tb9SAPXX3TSUzkxAjI/TEROV5X1pqzkbz7lLxSdCwU2ZduJbjldv8+vUc+XCLJxi3NfFvamYTOwS3O3/S8JdEF8nYSND6uIIi1szCKyvmpvLi5iYrOZcqFUubc0+Rdq3JLZcnApfkr4aaqeOhtXDLhsFL3RCanLSW1HFFub5efw=,iv:HJkGDyUDXxs2C2EtfgG2n2ZEMB3MClBm0o+mH/QTZ1o=,tag:vaG4Og1FTx5pUjhUkEZGyg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
