apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:2b/BRlwr4YaVodI2lUjrY5CMJ73MFh0V1t64LQhjZ1LIYVX+Koo7AjUKUK56pjjiV3nQquiN0hMAehjPi2v9IgJOJlJbB/F/Wr1Nnf2EH4VGvohJpQHJZJodAZDxvzEwNfPq/Gshh0Q/QVeCnBK95ByfETesvB0m0smaX0JrHxLEpbwaqpLrmJcJloMKrpBbdED1v6QHENQc6d27KghB6ibFs8cmJ3+r60yb+KrxwVlIdVyw+My0KMlDhmLubKSPFYQ3oaSYpq43Zg8xIau44O64wOzaXMbXnFxSAsGAYjfvkYRCMu5FVfhVAYEeTkCIUlyiGD6dpax2TsoPF7ZCWAxt1km3n2ihH3aD1w8LFzgYoR/iWFFkHfbyvzE5YOra,iv:ZklANOwK+yAF9w8ozalV4qmaqYu74Pq2JQ1IkMtDkKA=,tag:zJye/BPlvid4k52B0glDqg==,type:str]
    identity.pub: ENC[AES256_GCM,data:/JykXSKjr3XGqqOK9lk0xToPJbaQZnF7XZOSBkGmPv+9eQjGtzdoBAzcrhMcyxad0xn6kL+xNGbhb0ppY1Qm+vtwJbUC0GD/Yb1IcyiBItkJ/obIjnuCsqDzEQfzdkuwKEojDLwWk1INnWbviYMxAcxwcGEoXPQUABr78x8jO9DGu5rhICSZkMQSXetH/QZl3GCrJC6Vkn9pTQMi5msVLLrNga+vnxxQ+pqrc0m9BHF3Xjtf/CS99Wu3DEVEZ9YrITXA33PfFLotQqiMvw==,iv:WLehZpbBH6yHiU3l/YOlXzZ4VFsPn91DqlFF4PBpxIM=,tag:bEgaj7cOxEaE71BXhQxI5g==,type:str]
    known_hosts: ENC[AES256_GCM,data:3aN71JgcnLKSs9W4W28lrzWdv9Tbno9X3CbLmwFpp4EsNAWCDD/YQmpwL2cMmOWNeOz1uojb0dWHylyXDxlxAIK4AxOHzMMiP/NuJVJAmWYj0I+BaOItlH7x0tN4dOloE6ejYcJ6IUf74sa+zpt5PvmRMd2jxpLlkcQJiL3XMof+105A6M033MsPTJxPZX4PwJptk7FGsbZZCmQ3OZPVesCMqhCsTwNwNdJh,iv:/sw3Wu1Yh60HHUlMRVdwhK1ZGSoEnzKxvereK8HvJkk=,tag:q7evvLeGo90YIlq06g1s2Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6T2RURncwdFloK2RhQXMr
            UHdxQ1BDbDBPY2ZsZ256V3QzUUtiWWx4ZVRVClFqSlkyZlVWZlRHK2haWEhqUmlK
            WVRsMW5PUTd1RjNGTjdDL2htUnhRVEUKLS0tIHhkdU53UC9mNitOUWhqN29FRUJP
            dzdyTFdsaHU4L1F1NjFNYVVZN0pIbDgKuW917tGO/8CeVEWRvYQvriPikru54a+J
            ZqBrCmZVFqT3zZcHzgjSETNdigkp6RZlTmkYRVIylK3J7NV7B8xf6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T18:20:53Z"
    mac: ENC[AES256_GCM,data:LhSKr+rWlyx1QJl4MeBNSNz4UDj1SEOHhNFC4OVbSYPYTYgOG9Gy+NaoziZlo4us/hb3u3/Pgw35D2THRbUp1VlbwdvCscVDO6Tj3n1qVKGFPh4EzU/bZxCTcVgXzHNTz9eUYXWki55QziH9rRw0c/BC7610zV/Bk7GmhPiq37k=,iv:czviIDkui23OLQ6kdMF2W/6uBKXCpCWXh3Ws41/qlAA=,tag:Oa/pobwcFgC63m+FvFGdRQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
