apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:iR5AAyfDDQI1cPW+waoyWHhQkt/S7J+A69SRgHhxzQ7QcwAxDnAuOzXvro5qrpo7+K3mQrQastr/h3hfMuU4s1mESmBF70Ip5pYuMKl4mV5KPsy+Jyo9xpgsFtmPCNMAArW7Ke/N9lSmu+0H6jCris9DWruQvChjULxIKkSabNpGxzGn+ikwxAJJfWzHNHNkCd7nJbdARkK7HJ15gYDn1YHFSHY6o3HROr4eyGmjUqj2f98b1tYNwwYVzwDETefLMynfNuRCzczxQy9m5p1elXwgJSSCqB6GbePnNeIVcGBkRUHwWYZCtF+SWBDCEuHy1kldl5er8GQlpOg8XQqdPZkeFR4PhC9dotAWn9VSFhyGHMWwNUnylwLAkWkh3/XR,iv:xat0FFU20zTyMl2Dut2ph4uSFjYtWqxieI44pxPwxdE=,tag:6xZFtbezJXtCbRKbtCbX2g==,type:str]
    identity.pub: ENC[AES256_GCM,data:hNKGXYLIF4NAe+X3wCmkuB2En1mtSwGKNpXcq8n6iQytzTvviiUC7c3Ksn0S7aHIHKIe4otzIhfYzaM/9eRMHYp6G+mTqLJda5qXlvLSgk50rDMEFfymUc6vc0bEMSDrapnDu2mYa0xT+fBadHFROAlEt05wC+EyGhRBJGu+npczcwyLtDH6Lg7jT4Tsxci3NWCn0kMXVrCyeniMTQUtCe+TPSUF+N2yNk63C+OgPn1I1jWGNFN6aNfhO8J2fiQirExvFPPJ19rh2E6oPg==,iv:RBZ2QhXlVd1yn3GS2ZvbLZvepyZ+f0bdrwnSXx3Mx5Q=,tag:zzrct/Z+zifttF09dP2GjQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:JXqhz7J9IwFpdZlfW1Kl/7wJCcIBRp7LiqKCfCp/p+g8VRhIMISBWmc/1VStZ5apj3Lvc4fYeoFmGj4yafqacQHsoic0glyqS+GwHqXvVvvnmvA+bXxAzvtJeg9FjuPKgOtNIPLTgTEIE8ekqtiJsSChMbKUnkFg1BQmhE9PCW/qpz02VRY/1jdbblPuz1L6JvuK1vu9ML5QdG01dhu+th4w2CnwCfXN7MJ2,iv:oKSWTuivftXrWDWiRnqqxLo81ClVNVgLkFe2CpYRPaQ=,tag:KBSIfUbVlK7cIzD62HhUxQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuY0JYK1J0cGhWTXdsdTdR
            dTVGZHJnTlhBSGVBM2RVdlVOZThyY2E1MGw0Cm5vTmIwcmpiM3IwVnJiSnJyeWRS
            ZnovVXlsb2NQT3Vrc01DcmtnVVZFc1UKLS0tIE1RNFJXdmVmbEpCaDMvUE5yT0Q3
            YjVsRnZqNEVGN0sxY1pxUUJ4ZFF5YnMKsGbpqXXA7HsSAFZsY2d78iOJhCe7qGa5
            6gx8W4s1pLIigs2pqI+OuiQK08soArScIbBByaWArsk1rdy1OP3atg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T14:13:44Z"
    mac: ENC[AES256_GCM,data:288Xgc0Uev/28rA17uj7Mbk1XrknvI6aSHHzl4dhjEOhs0JPWueU7gw7FjLV2hLuwDa1YsUlXI4tqPAQMPR3178GCkTvvo/ypbUZsTYEQbMHHqCu6xlm+RyTkpoURQpEgf3dyD1G9ZNr01EgtlCCFyrBkcn3PmMTDvrNT3/iTZQ=,iv:6JRY+YqzGCLjX2CRBeFdxKIQiOdbEX7Mebn43KyOM0k=,tag:fF3P00c6SHT4ujRerxfVhQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
