apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ZRxi88yu7t9qSB0tNNYil0+MZbjM3md1D3HvRQsrgA9rxnUFhcxOJsJYkke9njAZ27EE5w6MuP0E54CTGdpiUJT3CmopNSOsgk3g8cULlG75/kB0VzbzEToeRxzveAqnqw1Z43H+BhwyBLcoqWHPljBDh/LhozOjEcrn54ggWvOPaaOi2MlO40uM0J4VeLF42gRZz6woZAmdDRhoQTih6kmybFY4Vzofqv/p5MMz0LfRW48tPbEy3RAuLZ0IIYdf0+BMeokJaQl3Hlv5qIkDT2T4uTv5mcuoLbnRpIx4EwwKsiYogd9uQ0y3XwUgG8GsTP6uapah6kQUpMDkgSO7GJxvqBrDzDutirdNc1arOmT7zWXvSXily24uENQT+2X8,iv:U9166f2EuacuubiDkTKskPMvmP91Ge2LrhVC0FzOlO8=,tag:9LhNzNfJ3amaFQH+bHAtww==,type:str]
    identity.pub: ENC[AES256_GCM,data:V+CylOjgrmE4qbLIVnlzYpylgXZpwBQ5ngIgjWWeqZlM8KI/Wh1neXA1EsXITHe4cELRYUkG6Ov4tH//s+NABHDQ4cJsfS0xCspNQ1wIfDFdW86K55APpBpCoJwuDCc1VUN4pyXGmPlGYQ63DsOyPEgsxNkENvPgmUUmfhM4/oSX9cF03NmBZqY8yqpJDngvQwowsyZVnI9meAlbMf8EfVs1OgZIPji3eAL1jPGRXLKFRN13H58QqHgogTSQYLXOLcx3nlCamWI3Ss+JEg==,iv:M3sjed5rsMshcv3/Azi8QMENKVEZmv9pGHWYT1igtkk=,tag:A3IFMqkF7LRGzYdrYxqVsg==,type:str]
    known_hosts: ENC[AES256_GCM,data:CcNnqtWi8s5+JJlPEMuKPcZq//09O62a6aBNt1CQFudWVCuMReMp+zJ7/eln9xdHCjNdKLU+XRIgV/V0Goz1u/HGOgA+yB60K2JBs2SO4DwBMXPK4mDgk3WPZ0vN97n8aT3kzE5SmcOw6sHdhOZn1r5qrQdVlAquRrQhLukBG0XnFYKMWdsNsAWa3UtOkY00IE18rCvXpzLRc3l3w6tanQ1Er0C+tjtcr3oq,iv:19Hm3O9RfX2PkVwn6laq5gA+miGugeOp6Y4YdNuCbzM=,tag:VyLaKn4ZPQgNXlxKNgW80A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZzdwQ0JhQXdrM1FtNFpt
            VGk4Wmh1YWdyRU11ZTVENFpxd1F5bk4yRG40CmpGNnVVV3N2QUk3ZHdGSG8wd1JV
            K2tlRHJNdVI0Znc0YW5vUUhTY2lOYTgKLS0tIHZrZTVpcG85L1hKdXJiWk1CUzE4
            YTBQeWxHbkVPejgyWG5BeUNTcjlRNWsKBnxfLJITWw1QhYtegMcw/+o6DTeQoJvO
            cd4o6YyZjsVtrEEno3PYsMAk4wFMZPibXDe3knhTQln8PE0VW88bUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T15:36:06Z"
    mac: ENC[AES256_GCM,data:CJWyj81r1yg4rXoXgal7IIF7vnCNIkvIxIxv7w7129liktHMw9gFVF0TSDUj1GnYyyBFg7dwqHAp00rAlDMWGKYNE1PThimXmB4mn4WiG9V6L6xaaczylAln2uneXZNvIa1kqya6M7c0iqGRpjxsAvxN2xy9gPbGXpfmyReBGiY=,iv:I8lAaVdYxaZx3LZN2sxseKbu/nbINcvBiwE/qVbtdGU=,tag:ZSPxYhLm+ETDbZd1+PG4jA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
