apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:u5YHc90hVyfIUbAXwxs6+avH2oTOjR60xPioIotpHq8WaH7aowpnVmgmTK2WgylLTWVAoLZsTYkDvEduSFtB7NCx706ys1QiIdI52xzOf4MTRo+Ly7jMwVD/TgBYCGjPrzYS2llDOpby1Ax7ccgPE5SlraUW7lfBO1BK0i8N60AE8Vc9HdAGPcuspq1z7BE6pbgbYKpTZexZoRnCkYXNf8MsebcYQekkeVr4TKr7u53M5nlW5t4dbwXCMl85CxorOvVszcO3ErfUXB5gwMqh+3FjRZpc7RtbIlUcO1qqKo5P9xclN9T+JbJMtqi0TfNOY44PHATQAvWG624zkqhOPXqWrkPhEmp3habXo0qPDRk6ukPez3Ev6OxNIyQX6vxY,iv:kVxd5CVvVdQ099fg/0aF4l3f35hEdjjTCv0BbzNiUT4=,tag:SHg/3cdjDwSHBisVr+DZ7Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:OzNdNuxRbj8GzKhJ8N1nYvFlrz7Rt+6I8EGvhqRqCA/I+7WZU0zJP26Li5IA4GlDHaxtgqDMGgxrArE2XY+S9mEnzu85lMuuLIt6uMBz56jcxh6s27/DxVkv1h3ZNl4QG9VglOMsDMxyDfVieKWXvnN9TdECEve2GBOcCR4NWDKKvLtcrdmvrdmVx2qVhIMDkjUaW51YEHRsP8dUN0uUtAwb4I/jpfAb+OnXbekY7J1Tj09FxMag+S701udiq9K4zlLNcGxkR63p6Bn3tg==,iv:GDL82ru+JvP0jrX0+vpOZEZSP6sEHjTis2d9Z3U7zr0=,tag:/pHp5+k6TZKipu9bSnnlWQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:AUNyn6llA0iKyxQ6iHPi4i5I107mimWtQhjOgH3ZkOGr+jdJe+SB6AkM+vSNU1INA76qhJjyXG8p/j4j2XfxPdAHcU+Mna7e9jAz1odOymSTX3a5k7T9ruwPnmilHivS78mnTs58NQJbWb+vrkx8HdkSzRTUuuD3+zCod0gwanwIqsXbvntcIuyF8h6odEnD+wHC7+Q6bdOFvC8vUJowZ/+e0Nq3b75ja+/N,iv:HxgeX33FmRflwSdGtkfHh1gNJ+fdZE3cZb8Ua+AD0gA=,tag:6CvGekTy3uRxkSmE6NtpPg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aXp6MVRYR3NwMTVFZXZl
            MUh6RWFyaVpBdnJSSmpsZ2IxeDl1YkVhbFFJCllRZUJVZTNqRWpJZDVCSklsNnlE
            a1VWYTh2TDRGVU5Yb3ptRnhZaGdWRmMKLS0tIEQyNWhQWHBjWWVSYllkN2xGOVV3
            bndzbTI3MHRXMzNNNDN5bWdOMW9OeWMKXdqXH1TnWwmm0H2nNgf10Gzuij2gt7gp
            mifjflykP9byRq0YyDWeRFHLVFTLFwbOp/BB4BGUbhGZuf+r9I82bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T21:14:35Z"
    mac: ENC[AES256_GCM,data:IwNbSSNWX/Op+uQ/PAiAg9xDSwZcRIwYhp+TvebYFsLXXjD3Qx23pDkhhsKeEMmHvbK/Tdy8rnwWy7wOsSlZ2upNhUYkevsCBIGJR0APrImNubapUoKh+9JGkJoTiKkqCy2MIhmSYX29RHQSxIJV1O1Sz0AK8eEYTpxF1ab/UsM=,iv:2BPvXpOIgnog8S8xW2qS8wLz2nSZmlsZuYNENbGwAzs=,tag:1eqxZaeYBY+V/Vqft9bgLA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
