apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:i7pKzFQIAIZ6lGEAEsFLiEi5MkURvgsnUR/DHnsIeeBAE75j7nBYExF+btmkZSKVKim3swMwpR9VX6ndHgL/qjgup5w6wxPfsz/tQzXmRiI7uAA64xvZ0kj6wDOgWlP3gLNVKsmWbI/Oj9hQhr6Zh65o7NbysOqOuYn/q5pk3mtd++EpGhAS+ELqwd7MvVDGsvT9n7AJtPRnSRAIrkGRUXiHRFmbJTSUDHew2P/rYTXs42jsxV2phigO3OkWd0QiwV5YxpqpEt1CLTwK9ENzG6BOXW4yDf4/t+husyCqJl/+YjjcZmfQGjv7juE4nvL3AfwtUhvlqUjfvHfq0NEgIQFnmSChYzX31+dbD6oSBDRN9tI550o9hLHpjVOdjAt4,iv:sRa76SXxRGMOC2YiziTUoFpHqZvE4ZbwJN3bbVnYfFQ=,tag:AD0pjx959aBBdyiTFXy7ug==,type:str]
    identity.pub: ENC[AES256_GCM,data:MEZd4XP8opAS6nYCLu5hORwEf1Bzu30dDKHcnjkFauw+ahGgDNXUx39Q5WtbOYnCw+Asi0WTGKCuVUHnRy3K918NtmPg9Y1+TtfEjRUozK4Zg/ctjAgkoGpp4pEvJsdYPi32Cda3WmchWHvLcAf6cwKP3dDaQyxczYKIQ1arX23UuLPZpqBTHVsP82MTXdoIzBgg2Dy9q4T5iDl4dnXY+UojxemMadUax/yEOHo+vX87wqfwAHjG2K5Odk5Ij2dzrrxetlKLdKT/L042fQ==,iv:W5KPtmv5DLMPrgWZLdUN/8fTVeeydBeoasANEr5W5cs=,tag:AHJc1K/vVZndoM9TZg5Fnw==,type:str]
    known_hosts: ENC[AES256_GCM,data:++8QUim/eYCjmdD82wIsAFIPiwtPE0RHlzkqZrUFVy6Bu4pR0WdgaEb0k50yhI2NqufT+FlMJvZg46cfywUkWL+ZiPVn7iXz92EAfHk8hNIfXUSWWRAKTKdE+29b7/QaNGCHhkccOfmaVB9i12Wb4l72fiIh23FhnwIpq2lcKgWbgjvLRRc83hGCNC2Ecv9/QHlzoo1t9nmINBuXGuETCCW71c0igpCRWcyc,iv:thSYsRxIPMI2EslnnrfeoW70GKSylGrNQcGS/rQiwFw=,tag:hsDzJNCnikuhKlpV/2k74Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1U09TQjZ3RWZYdmVNZmpn
            WnpmV3BrdDFWYURDNGlhU2lmdmJtRXNTaWdjCnhFTVIyc1BtaWpXbEowOWxzQWlY
            VnZWYzZ5QTRnbTY4eVZaSjkvRDRrUUEKLS0tIG1TUEVwVnovcUxydFhvcmdpTTBM
            dmJEOUFueFpaeVJTU3kvYmt0M1p6RjgKfIlbiLl3fOtj2XWofq5ax12ob4Ykcv9+
            ckrm4lhYj0l3pz49nHFP8IO1l2Mnxf5mXhXFiKBfukHlmBZd+w2Ujg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T18:12:53Z"
    mac: ENC[AES256_GCM,data:0pQrp+Ca4GLnvHJEyDdupgKyd7nBHz44S5b37/krNQVTKle6PCK38CFYlw4MOmYIZMuLc9Zn0OkBh8EBlUw2ocgzjKJ3pP64QI1YxzANPO5SnBHYCGUrTo55anrUGMzS3ufWDTJDmtSrMew5m4h9qSuCaLv83MB9K1zFByG8t88=,iv:gb4lpI8DzOm9uYyVADiG9UfE+K0G4eAxivK9kh0/A20=,tag:psjS42J49J8IzQEhpcziEg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
