apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:R0A7o/U91ncfFLkJAzgb5KnzvoXlhPEU0LKATHxHQnWmdzbQ/ZAridSvGBJqXvO8C0t3ps+Dhlc0GbbYV9o7yrVprK+gXsEzoXh1iBr2G0hMocV+aeKIOMpwKKEEU/IoMNmElb4z3l/0R/pYngXBn87eCaovWniRQgUFMZ8Dgl1EBfFdj/oW6OZ4mAfOk7yoETZepg3mAzRbwCLoGRw+VMrsvFNpLAGbxcfBFcHhhAjaHoxB1P3kx+qF3VYerbefl0tDLqDlPvILNWLu6EqG4hcR1VfxPArI1F0l4zIesctTvCDXwNz1LujJiAJZSVSNwPR8+lm0U4HWd5BafXJwtsW0+uXrq6U/jy9Y9EaU0+ParllSv53QqTH4R5RQWs1d,iv:q1VT9CMdT73N8CRyXx0KwBTh2M6DM9om8imNfPuKzVk=,tag:/2XbcIapAcmI7hcU0+YRJg==,type:str]
    identity.pub: ENC[AES256_GCM,data:Zos8JhvGV0sE9qqwWj4KAeCsYm4rPRf5dGsfHvlQWj8cVBvDuOwmTBcbK6dMiRXkRi9OTb5qcbEQWi2NLYrapQIuhEKCbCQu2zJDg8HelFBwOWCAg58rfKb2sa/JViso068ENdrCu/lBf+9qqzPevW6Obv9ufwuzdpyYVzYfCeW8QrkAxQOIzLQxUuZeAW/bR9P1608XFBM2wLpsJw48/dLqQUoX87aYqPi7/8ftVwsilnmMnc1hBKbaabTz19B3fsp/r9M/AWwirc6qQg==,iv:8ydHrujFH9ULSDFG9mgehLZOzJ5/NP+bieo3bkV6H7I=,tag:YRAHLsxro7XIUhGQILLCGQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZtSh5ZN+CzcgyHAlqGs+xShT6XKnuK8x65qr+EmqYD9ujCp3l8a051NaucKnr7V/FjjpvAvenWRTDUreW+dxAGvWyp9r9YK4/qJIscckk63sy5iu6mFTldBSZgNeCLfT7TJTxMuoqIirYaWevJ2EJU3CMmXqxtLWbE2L++jsC+Svuqwu5GJkzvsZ96A2zX/eM9QyT4S/OWmctUSyAeQ5w9ifJUENsJVG0/TL,iv:BPwJNT72g3RoGvY9LjZ6UGH6cN2zH+5G7a3T45gJTLg=,tag:Z3aSYIYTgPZUfbk9w99UxA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdTN1WU41VlZpRldmZGR1
            bWZiVG9ReEh5UCtsWUk2czVXSVdXaE9SaTAwCkhaL01xRTJIcGV5SkN5QjB2bXNW
            TkRDMVNDQzVFZzZodDRGN292RlBDKzQKLS0tIHlMYi9qOFJuVVE1N3FSVGZXWFF5
            M0o5OS91YUViSzdXb0JoUUR6VkpBZk0Km1l2QnEF41Rpl6ErYxXE8eaURLBNcKpb
            epDvsHUQiuoNWKxyw8kbeP/uXXLUdNWBX+ungl0OO/Q8cvZhA169Fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T23:28:07Z"
    mac: ENC[AES256_GCM,data:qAppgg8H1lNyrGLwbxydOV8U3RL19VkWP82rBSf1szBQAVu6EJ5Qp3IKz1v2JGsdXuiEYVypKCF4UP2KdES9+9U5XHiEQWzIQgiHw4mmUrf4/gojTO19H8S5Ca/kOoid/UkooJzjZh+ZR6Uh6PlGPacfuiwBSk7+PHcmbZWPER0=,iv:S4z473aLe+80m5p3ZtAlT1CoO6l98a5t2IJ0J0BdNjk=,tag:YotpfSP8j1+4bwK5BRFegw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
