apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:UmDY4cJSjFf/zmf7mCus/V1zAj9KIByAD6LIN259SS1yRLKfkQcRrWyiiyEEfmQdgBm626undQqvBZhtH7Few00yRMzvsl0HVZwSU+D/McG5h9XJOsGJ26CSMQOO29oOzRg1xoyKUxnQMKn9uc5xKaQZkByiclkKXSIG1/eNwolfPr3iFPCcLl6bh0TB5Kr4V0uogikrMh56+t66WF4g+UDOtDbEFY8njoBpie0M0IUBkolnYfMNRixSnR0udp4UR+4ra3IfxXdg7mpXA+LuxjDbw0Tls/pbSV0c4uM5IjpZbGgy+/FnJH4IIFK6N8ImgwXiAbfPsCt6iuevOizu5w1MP7lRAo704k6pncSglSjNgTZ72nJlOmOTHIqAyL2p,iv:jFJvUDpsqYFtcuIgcCFLJcgL1qNwiUqIXOOaMdIGNG0=,tag:VN13BddJedt1O7+ZzmoSlA==,type:str]
    identity.pub: ENC[AES256_GCM,data:JFA7TFRBRv18DmbTqzyS37vYZ70W84XFBX6fPCVZivQH8iQL3Dfqjy1k/qxNv27F8Ve1dgWN1BOU2xVHz1/dpulqC+MHC55Kx9ghncVbRfp++a2zD+qbiRZu64Xr5lI0yW9id3M5YEDNAwkuc6N3z4fYshvNIyi4w9mkasvqmUpgKiLWoXmTykg60PTRG0tf+D0NnN7mXjmjQTcgPgNNkVwLmyQipFEiNyAAc3PQ3qDFpTuw9eUtxG50hBO9tiWeIimAooVj5b1vqyQkVA==,iv:4Oje/BEQYQEmk9dSV8+ahN39bBmRRJ/4PQiSeXVLJIs=,tag:KRTvICoHBppa84loVwhP7g==,type:str]
    known_hosts: ENC[AES256_GCM,data:zbT8TlPslXTYPCdzi7S2YhR1IWNqjo+G1vIHlrVafVBZjbj9S8cw6x/mORLHth9CjwPtAlFJEvzHPTxTUYNjq/sspW+TLByeucVYGAJjHhjB4a71wxjtu8OWBuKH6RTGjf4HHXo10Pfs6HVH/19OYOLTzdwRiuIyeTmxZW1zis50nhlmrPAtLgsyvO8nearNONDLDZKRzafIKxETwCMJ01eQBso56Mmcz+fT,iv:mWKD6MOhdt1kfTJtIJcR7/rgosSAXlMqg3Vb9yANWys=,tag:dWMkTOJSXcYuNj17UnU2Kg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwV1hMZ29heDNEd004eHox
            dC9ZOWs5ZDIrRDB2MHlhQ2dQaG9KNGJCU3dzCkpxZmVrTEpieFc4N3NGUkRvSmho
            RlRaWDJWY0ZROFEyb2cwVnZMOTFDQ3cKLS0tIHpnMzhtNWhKWjFoNkVjb3JIanRG
            YWJ5UmVxaUVnb0l5QzIxNURVSEFYbEUK0yWTxex/lOu9SJO5yyqget4ROIgGjZUx
            sLa0JcG0pFw62XesDuTCZzSDbkKTIxYeXzMHmiI+dcT6Ae5ZvB00wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T19:01:14Z"
    mac: ENC[AES256_GCM,data:djlvsVKFaSzw8cOfOlLVsdAlSvqV86BNDMQNbSgP4HEag0Uqk8xKvkN9XzfpvOAC2JSM3TEbapCYUTwGt6SHc6K1Flx4+n9H/PA3GgUf7PHvSNfWp9zhGFLg7/c9wW3dwgFHRBOjhtpzUPApc3xV2cMxNtucCa/Acvi0TrfPBXE=,iv:1d1P1u543hr832C2sstNXTKhuYxMl+m/m3yroTVD91Y=,tag:NVeXh0Q2/fYvtHHCSrtolQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
