apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:P/xtkK99LxzIPNohwiXu4xQimI3FkzmQbmRtwi7WVl6QWi0ucsGbpHBLpyY9Vi2IcQXJ/0DNImkUBaqsxUSfiGCvYVUwMsgZATJNBqumuU5RvJYDtDASnAYItfimUspoRSrn6WfS4Q/p9uD0qjtM3lZOsuMecxU+o/KBpFU3neFgPRDDu36HVLc0/qZTzXeFvbipR0sYlBU5HHpddgIrfV+XJK1HpJdaV3cZri91uLjgaovVCzLevUOG/fzDXQDXtROg7ESgJ/uwwXhMeNU8O6eg/c4P4n9GZnJt+nk0CelsByZ5CKESIaWnx0D9gPM9Cuc/90RLmQ2cn0rBt0wcznPWAcDFjmZwHODMhEAQBDefro3q9LQ5F08GzLpmYNFN,iv:Uqzw4aW5d8hnh5K5ZFs12LIYe168w67KNVbluOASPWY=,tag:Rj/Cik+IrzQAgN4vUPh8Iw==,type:str]
    identity.pub: ENC[AES256_GCM,data:pvZBUQ4aOZpJh3RbaBtoz1Yjhn1sWHFftElpRnXL9luRkWfVcj4TIXrIkicLF/JCJb/ZphqWtu8uT+QYXXRTokRODXO995AK6o6evOTPmANDFN/vvFHj8TS6qA4085OeYBIVMZJlG1UFJCM85VTmmlsVBx81sw5ZoJxPoFz1g0Pb13a/5yK3KPHNr3CmXTdUa7d06P9uKnq47qHxmwU0+lNXzxd2ngJ8FQ5Vhi/lvA572DT7P+n/qo68rW3pjVgXqFwcPlwepBhNCsybwQ==,iv:Pi316nsa8HNyDFdedd846lJaCa1851C6tIrKaULCbVk=,tag:/SbHja2Ucq+QZV1GrF/RwA==,type:str]
    known_hosts: ENC[AES256_GCM,data:dS0yi2nLxD23K0C8aIcSsCB4vfqO3H3qSaBGvuZ5+oy4rg0LKrAgDm1yV1+c2QW8H3R2nYLA7rUElxQcngGHYHVftCsmqukseQuo2dLc+QZ22aOeB9eQCd5OXYWEP9KWtPB6aHzV/gT14vjBmHQEgD6atmCpKlHV7PYD98l6qPmpMHN2260EHGqRdIKHUe2awX74+Vdle2kxoufbUL0pPkI7ZCuq/Gfcso0c,iv:qZZLnBi1c5gJlV+Eupn/DN1hn7iZjsXzyYut2600L7E=,tag:cIbpF8w6dPZZA3K8VJaSrg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1eEZFd2VTK1BaazEzY2pG
            Tlo3WWdES0NEdmp5ZHFsMkZvTHJEWlZ2RlVJCi9nTkYzclo5eUl3YnF3b3plWlFh
            bjBheGNwb3lhWm9rTjkxMjRQT1BmbDQKLS0tICtqTUxrL0V6WFJaSHdxbVF5TGZR
            Um5ielJ0dXQrcWlNRUJ5TTlhbnliaTgKBRtMDMV1ZOm2sXINvuub0KqKExpIdyid
            bkUSl3hA2fhQ230BMn0H+zcYOWRLdJIM+d6Aon6R+6BnDTW22x3kdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T14:23:53Z"
    mac: ENC[AES256_GCM,data:3uCP63K0hMr5xP11wiUzOAymqgtJfbdSXepeYisoLVUseXhmIrWk5QhdeMOn41uNoHUQowKpO5pgaf4kdTGlmMGw2CNAXsdhpMlfppAzKkWeF2wvHfVS9FYHQn2WDjTTIkDOHsRBthjHXtGvPPq12+ZR9jRC5+s5ZAPsnjoUVwk=,iv:Tv3SCh2U4FIRma3o5T2rz8cjwlj2jeH4M58twSPWKJM=,tag:FwxaKbJadjEOf3ZWgKIFMA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
