apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:8Yk6d0y1oZF4wKBNiUMz6VnyhHmbaDva3Q/gyCenLlucWV8iU+iVDV72hqhBllXJwjsm+reUldShJV9tk+yhos2LzJyxgxvy38vJ7OwvPmy+wDW8fur6QY2YeeWkVUSu7OxnDq4fMifgKa1/zPXzADqv8MdZFsj+Tnf/Jndao4Sf9TnJKhMsjkhttIMZpDsK/m4L6zRU3+zd1YrLK1+BdGdAc/LgzdcZYO5fu7dNXRYkx4Ss4bZ+PMyzd2YgzkDh56vZ6sDV71vitwjEdNMRSlvKr2O9opEC+dbYBumu9egIC+HARquI5ccnfnRKfRum7g0lTVgmlKaYm+xoC8LgbMtjZiOiaN87d6XhcK3C0djkklPYHmRCTcCJWmf9olJo,iv:xzbYpVV61op6SQ//v0sD9x68MWBpMnvV1Sc1IQ06clk=,tag:krxsFp3jtaL95Sfptch40g==,type:str]
    identity.pub: ENC[AES256_GCM,data:MMpRVmgScVVDQKsfCIt7XKsNa54ZvYTovdvsQILF3Dn8K8tWdqpJdtnvT7NSVMRtWTlHJOUYJPyjxn8cbCMB/GLNAhIRTjynzpOORB8E4MZSGch8OVqzFUXPFllXA/gfx4v2190BRPOEhyh/Ltngt8iy/TSTLO2pRsK2mN+AmF6OGh83QJ8Iy3/7f/CVG+LaoP1HGxqx32zS8q+hxseHfyyxoOj3qBNsD+qx1rmt2Id2MaIJQ8brsdbfOzmKZDJhFDNP1yfJpzpkhGhY9w==,iv:LjURj/VtzL0bOTMpqOQVSbRPDLqFGh5/ZgnMORbXiYs=,tag:v0IiJGkNXkB27JdBoI2jVQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:4P1o+qKcykhGEoj4IGTQw+nyznH6CoRbZ6VyBQsvtPGOxt9p1+e2DEMpR2qsjCgI/Fg1QZW5KixA0f3P1TKpnWwxZp3PfZB09TWXVj6bJxP7REGyzOo6Uugj9wiCMRDIs+cJGuKf+DukoBggsbf6lR6tfKTm5M8rzXdIwwcD1tJBjyY1C8DpugwLLEkfb6ZMonfQqaRk6xfNOgvuTf3en/1ef6XAr/woVdhV,iv:FQHdHTr6xhbP/jL9dk9lp5UHt96Kkqilpw7RRkeOFfw=,tag:c5NTrN0gv5ERIPh/9fRxkA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUU9WSmdIdjNyRUhpdnJ5
            U2ZhZlhDMXpJbTQrTGhFMTExaHZ2Y3R1WnhFCkFxdk9GUkg2eVV5TEdTendOMGRn
            dWFkbUZEZzZaeG11ZWllVE1UNUlhblkKLS0tIC8wQW9velRabVNtcmlzcHhVeUYr
            V05ORnZrSjhwdTcwSlpDSTJYQ2d5YUEK+sLWEicBh/nz10WoPRogNQLO1Ts90QZE
            yLx6CyL6tMCIsyJqb+NNpyW1quS2YoRYWkVMwod0YJSoTYU0o0PZag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T16:22:24Z"
    mac: ENC[AES256_GCM,data:mwuvv+dJoYCJifOy7nQtr7Wm7tmRNuS3d4/Z9FsXEZGQHVvao9myFiCj1Gm+ZTbKZJEFT2GZDoWvhxwQ+kKV95zIhK7gVUn2CuiqTLWFDi4yUp/qcNIL4/97Aowdg1qUCo+t4csinkWhDPYQ5ha4lZkCHYBA3Xz2aB4gEu+48gg=,iv:E92AyYK6Vlrg3uvDgwl8ufu97pMrw4ARg6x0DwXDiEA=,tag:DAbL1dZSy7cYvGQK30bZtg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
