apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: air
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/external/air/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

